
---# nambah user
CREATE USER 'gd_user_akunting'@'%' IDENTIFIED BY 'nyungsep';

GRANT ALL PRIVILEGES ON * . * TO 'gd_user_akunting'@'%' IDENTIFIED BY 'nyungsep' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;


