# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laporan/ui_laporan.ui'
#
# Created: Tue Mar  3 16:43:10 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_st_Laporan(object):
    def setupUi(self, st_Laporan):
        st_Laporan.setObjectName(_fromUtf8("st_Laporan"))
        st_Laporan.resize(679, 486)
        self.st_Menu = QtGui.QWidget()
        self.st_Menu.setObjectName(_fromUtf8("st_Menu"))
        self.igr_Menu = QtGui.QGridLayout(self.st_Menu)
        self.igr_Menu.setObjectName(_fromUtf8("igr_Menu"))
        self.fr_Menu = QtGui.QFrame(self.st_Menu)
        self.fr_Menu.setFrameShape(QtGui.QFrame.NoFrame)
        self.fr_Menu.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Menu.setObjectName(_fromUtf8("fr_Menu"))
        self.ivl_Menu = QtGui.QVBoxLayout(self.fr_Menu)
        self.ivl_Menu.setObjectName(_fromUtf8("ivl_Menu"))
        self.gb_Menu_Laporan = QtGui.QGroupBox(self.fr_Menu)
        self.gb_Menu_Laporan.setFlat(False)
        self.gb_Menu_Laporan.setCheckable(False)
        self.gb_Menu_Laporan.setObjectName(_fromUtf8("gb_Menu_Laporan"))
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.gb_Menu_Laporan)
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.tb_Menu_Laporan_KasHarian = QtGui.QPushButton(self.gb_Menu_Laporan)
        self.tb_Menu_Laporan_KasHarian.setObjectName(_fromUtf8("tb_Menu_Laporan_KasHarian"))
        self.verticalLayout_28.addWidget(self.tb_Menu_Laporan_KasHarian)
        self.tb_Menu_Laporan_LabaRugi = QtGui.QPushButton(self.gb_Menu_Laporan)
        self.tb_Menu_Laporan_LabaRugi.setObjectName(_fromUtf8("tb_Menu_Laporan_LabaRugi"))
        self.verticalLayout_28.addWidget(self.tb_Menu_Laporan_LabaRugi)
        self.tb_Menu_Laporan_Neraca = QtGui.QPushButton(self.gb_Menu_Laporan)
        self.tb_Menu_Laporan_Neraca.setObjectName(_fromUtf8("tb_Menu_Laporan_Neraca"))
        self.verticalLayout_28.addWidget(self.tb_Menu_Laporan_Neraca)
        self.ivl_Menu.addWidget(self.gb_Menu_Laporan)
        self.gb_Menu_SubLedger = QtGui.QGroupBox(self.fr_Menu)
        self.gb_Menu_SubLedger.setObjectName(_fromUtf8("gb_Menu_SubLedger"))
        self.verticalLayout_29 = QtGui.QVBoxLayout(self.gb_Menu_SubLedger)
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.tb_Menu_Laporan_HutangPiutangPerusahaan = QtGui.QPushButton(self.gb_Menu_SubLedger)
        self.tb_Menu_Laporan_HutangPiutangPerusahaan.setObjectName(_fromUtf8("tb_Menu_Laporan_HutangPiutangPerusahaan"))
        self.verticalLayout_29.addWidget(self.tb_Menu_Laporan_HutangPiutangPerusahaan)
        self.tb_Menu_Laporan_JualBeliPerusahaan = QtGui.QPushButton(self.gb_Menu_SubLedger)
        self.tb_Menu_Laporan_JualBeliPerusahaan.setObjectName(_fromUtf8("tb_Menu_Laporan_JualBeliPerusahaan"))
        self.verticalLayout_29.addWidget(self.tb_Menu_Laporan_JualBeliPerusahaan)
        self.ivl_Menu.addWidget(self.gb_Menu_SubLedger)
        self.igr_Menu.addWidget(self.fr_Menu, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(430, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.igr_Menu.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 236, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.igr_Menu.addItem(spacerItem1, 1, 0, 1, 1)
        st_Laporan.addWidget(self.st_Menu)
        self.st_Laporan_KasHarian = QtGui.QWidget()
        self.st_Laporan_KasHarian.setObjectName(_fromUtf8("st_Laporan_KasHarian"))
        self.gridLayout_2 = QtGui.QGridLayout(self.st_Laporan_KasHarian)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.fr_Laporan_KasHarian_Judul = QtGui.QFrame(self.st_Laporan_KasHarian)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fr_Laporan_KasHarian_Judul.sizePolicy().hasHeightForWidth())
        self.fr_Laporan_KasHarian_Judul.setSizePolicy(sizePolicy)
        self.fr_Laporan_KasHarian_Judul.setFrameShape(QtGui.QFrame.NoFrame)
        self.fr_Laporan_KasHarian_Judul.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Laporan_KasHarian_Judul.setObjectName(_fromUtf8("fr_Laporan_KasHarian_Judul"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.fr_Laporan_KasHarian_Judul)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.lb_Laporan_KasHarian_Judul = QtGui.QLabel(self.fr_Laporan_KasHarian_Judul)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_Laporan_KasHarian_Judul.sizePolicy().hasHeightForWidth())
        self.lb_Laporan_KasHarian_Judul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setPointSize(18)
        self.lb_Laporan_KasHarian_Judul.setFont(font)
        self.lb_Laporan_KasHarian_Judul.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_Laporan_KasHarian_Judul.setObjectName(_fromUtf8("lb_Laporan_KasHarian_Judul"))
        self.horizontalLayout_13.addWidget(self.lb_Laporan_KasHarian_Judul)
        self.gridLayout_2.addWidget(self.fr_Laporan_KasHarian_Judul, 0, 0, 1, 1)
        self.fr_Laporan_KasHarian_FA = QtGui.QFrame(self.st_Laporan_KasHarian)
        self.fr_Laporan_KasHarian_FA.setFrameShape(QtGui.QFrame.NoFrame)
        self.fr_Laporan_KasHarian_FA.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Laporan_KasHarian_FA.setObjectName(_fromUtf8("fr_Laporan_KasHarian_FA"))
        self.gridLayout_13 = QtGui.QGridLayout(self.fr_Laporan_KasHarian_FA)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.lb_Laporan_KasHarian_ = QtGui.QLabel(self.fr_Laporan_KasHarian_FA)
        self.lb_Laporan_KasHarian_.setObjectName(_fromUtf8("lb_Laporan_KasHarian_"))
        self.gridLayout_13.addWidget(self.lb_Laporan_KasHarian_, 1, 1, 1, 1)
        self.dte_Laporan_KasHarian_Dari = QtGui.QDateTimeEdit(self.fr_Laporan_KasHarian_FA)
        self.dte_Laporan_KasHarian_Dari.setObjectName(_fromUtf8("dte_Laporan_KasHarian_Dari"))
        self.gridLayout_13.addWidget(self.dte_Laporan_KasHarian_Dari, 1, 0, 1, 1)
        self.lb_Laporan_KasHarian_Periode = QtGui.QLabel(self.fr_Laporan_KasHarian_FA)
        self.lb_Laporan_KasHarian_Periode.setObjectName(_fromUtf8("lb_Laporan_KasHarian_Periode"))
        self.gridLayout_13.addWidget(self.lb_Laporan_KasHarian_Periode, 0, 0, 1, 1)
        self.dte_Laporan_KasHarian_Sampai = QtGui.QDateTimeEdit(self.fr_Laporan_KasHarian_FA)
        self.dte_Laporan_KasHarian_Sampai.setObjectName(_fromUtf8("dte_Laporan_KasHarian_Sampai"))
        self.gridLayout_13.addWidget(self.dte_Laporan_KasHarian_Sampai, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem2, 1, 3, 1, 1)
        self.lb_Laporan_KasHarian_Dari = QtGui.QLabel(self.fr_Laporan_KasHarian_FA)
        self.lb_Laporan_KasHarian_Dari.setObjectName(_fromUtf8("lb_Laporan_KasHarian_Dari"))
        self.gridLayout_13.addWidget(self.lb_Laporan_KasHarian_Dari, 2, 0, 1, 1)
        self.lb_Laporan_KasHarian_Sampai = QtGui.QLabel(self.fr_Laporan_KasHarian_FA)
        self.lb_Laporan_KasHarian_Sampai.setObjectName(_fromUtf8("lb_Laporan_KasHarian_Sampai"))
        self.gridLayout_13.addWidget(self.lb_Laporan_KasHarian_Sampai, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.fr_Laporan_KasHarian_FA, 1, 0, 1, 1)
        self.fr_Laporan_KasHarian = QtGui.QFrame(self.st_Laporan_KasHarian)
        self.fr_Laporan_KasHarian.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_Laporan_KasHarian.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Laporan_KasHarian.setObjectName(_fromUtf8("fr_Laporan_KasHarian"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.fr_Laporan_KasHarian)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tb_Laporan_KasHarian_Cetak = QtGui.QPushButton(self.fr_Laporan_KasHarian)
        self.tb_Laporan_KasHarian_Cetak.setObjectName(_fromUtf8("tb_Laporan_KasHarian_Cetak"))
        self.horizontalLayout.addWidget(self.tb_Laporan_KasHarian_Cetak)
        self.tb_Laporan_KasHarian_Kembali = QtGui.QPushButton(self.fr_Laporan_KasHarian)
        self.tb_Laporan_KasHarian_Kembali.setObjectName(_fromUtf8("tb_Laporan_KasHarian_Kembali"))
        self.horizontalLayout.addWidget(self.tb_Laporan_KasHarian_Kembali)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout_2.addWidget(self.fr_Laporan_KasHarian, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 330, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 4, 0, 1, 1)
        st_Laporan.addWidget(self.st_Laporan_KasHarian)
        self.st_Laporan_LabaRugi = QtGui.QWidget()
        self.st_Laporan_LabaRugi.setObjectName(_fromUtf8("st_Laporan_LabaRugi"))
        self.gridLayout = QtGui.QGridLayout(self.st_Laporan_LabaRugi)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fr_Laporan_LabaRugi_Judul = QtGui.QFrame(self.st_Laporan_LabaRugi)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fr_Laporan_LabaRugi_Judul.sizePolicy().hasHeightForWidth())
        self.fr_Laporan_LabaRugi_Judul.setSizePolicy(sizePolicy)
        self.fr_Laporan_LabaRugi_Judul.setFrameShape(QtGui.QFrame.NoFrame)
        self.fr_Laporan_LabaRugi_Judul.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Laporan_LabaRugi_Judul.setObjectName(_fromUtf8("fr_Laporan_LabaRugi_Judul"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.fr_Laporan_LabaRugi_Judul)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.lb_Laporan_LabaRugi_Judul = QtGui.QLabel(self.fr_Laporan_LabaRugi_Judul)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_Laporan_LabaRugi_Judul.sizePolicy().hasHeightForWidth())
        self.lb_Laporan_LabaRugi_Judul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setPointSize(18)
        self.lb_Laporan_LabaRugi_Judul.setFont(font)
        self.lb_Laporan_LabaRugi_Judul.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_Laporan_LabaRugi_Judul.setObjectName(_fromUtf8("lb_Laporan_LabaRugi_Judul"))
        self.horizontalLayout_14.addWidget(self.lb_Laporan_LabaRugi_Judul)
        self.gridLayout.addWidget(self.fr_Laporan_LabaRugi_Judul, 0, 0, 1, 1)
        self.fr_Laporan_LabaRugi_FA = QtGui.QFrame(self.st_Laporan_LabaRugi)
        self.fr_Laporan_LabaRugi_FA.setFrameShape(QtGui.QFrame.NoFrame)
        self.fr_Laporan_LabaRugi_FA.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Laporan_LabaRugi_FA.setObjectName(_fromUtf8("fr_Laporan_LabaRugi_FA"))
        self.gridLayout_14 = QtGui.QGridLayout(self.fr_Laporan_LabaRugi_FA)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.lb_Laporan_LabaRugi_ = QtGui.QLabel(self.fr_Laporan_LabaRugi_FA)
        self.lb_Laporan_LabaRugi_.setObjectName(_fromUtf8("lb_Laporan_LabaRugi_"))
        self.gridLayout_14.addWidget(self.lb_Laporan_LabaRugi_, 1, 1, 1, 1)
        self.dte_Laporan_LabaRugi_Dari = QtGui.QDateTimeEdit(self.fr_Laporan_LabaRugi_FA)
        self.dte_Laporan_LabaRugi_Dari.setObjectName(_fromUtf8("dte_Laporan_LabaRugi_Dari"))
        self.gridLayout_14.addWidget(self.dte_Laporan_LabaRugi_Dari, 1, 0, 1, 1)
        self.lb_Laporan_LabaRugi_Periode = QtGui.QLabel(self.fr_Laporan_LabaRugi_FA)
        self.lb_Laporan_LabaRugi_Periode.setObjectName(_fromUtf8("lb_Laporan_LabaRugi_Periode"))
        self.gridLayout_14.addWidget(self.lb_Laporan_LabaRugi_Periode, 0, 0, 1, 1)
        self.dte_Laporan_LabaRugi_Sampai = QtGui.QDateTimeEdit(self.fr_Laporan_LabaRugi_FA)
        self.dte_Laporan_LabaRugi_Sampai.setObjectName(_fromUtf8("dte_Laporan_LabaRugi_Sampai"))
        self.gridLayout_14.addWidget(self.dte_Laporan_LabaRugi_Sampai, 1, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem5, 1, 3, 1, 1)
        self.lb_Laporan_LabaRugi_Dari = QtGui.QLabel(self.fr_Laporan_LabaRugi_FA)
        self.lb_Laporan_LabaRugi_Dari.setObjectName(_fromUtf8("lb_Laporan_LabaRugi_Dari"))
        self.gridLayout_14.addWidget(self.lb_Laporan_LabaRugi_Dari, 2, 0, 1, 1)
        self.lb_Laporan_LabaRugi_Sampai = QtGui.QLabel(self.fr_Laporan_LabaRugi_FA)
        self.lb_Laporan_LabaRugi_Sampai.setObjectName(_fromUtf8("lb_Laporan_LabaRugi_Sampai"))
        self.gridLayout_14.addWidget(self.lb_Laporan_LabaRugi_Sampai, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.fr_Laporan_LabaRugi_FA, 1, 0, 1, 1)
        self.fr_Laporan_LabaRugi = QtGui.QFrame(self.st_Laporan_LabaRugi)
        self.fr_Laporan_LabaRugi.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_Laporan_LabaRugi.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Laporan_LabaRugi.setObjectName(_fromUtf8("fr_Laporan_LabaRugi"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.fr_Laporan_LabaRugi)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tb_Laporan_LabaRugi_Cetak = QtGui.QPushButton(self.fr_Laporan_LabaRugi)
        self.tb_Laporan_LabaRugi_Cetak.setObjectName(_fromUtf8("tb_Laporan_LabaRugi_Cetak"))
        self.horizontalLayout_2.addWidget(self.tb_Laporan_LabaRugi_Cetak)
        self.tb_Laporan_LabaRugi_Kembali = QtGui.QPushButton(self.fr_Laporan_LabaRugi)
        self.tb_Laporan_LabaRugi_Kembali.setObjectName(_fromUtf8("tb_Laporan_LabaRugi_Kembali"))
        self.horizontalLayout_2.addWidget(self.tb_Laporan_LabaRugi_Kembali)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.gridLayout.addWidget(self.fr_Laporan_LabaRugi, 2, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 262, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 3, 0, 1, 1)
        st_Laporan.addWidget(self.st_Laporan_LabaRugi)
        self.st_Laporan_Neraca = QtGui.QWidget()
        self.st_Laporan_Neraca.setObjectName(_fromUtf8("st_Laporan_Neraca"))
        self.gridLayout_3 = QtGui.QGridLayout(self.st_Laporan_Neraca)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.fr_Laporan_Neraca_Judul = QtGui.QFrame(self.st_Laporan_Neraca)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fr_Laporan_Neraca_Judul.sizePolicy().hasHeightForWidth())
        self.fr_Laporan_Neraca_Judul.setSizePolicy(sizePolicy)
        self.fr_Laporan_Neraca_Judul.setFrameShape(QtGui.QFrame.NoFrame)
        self.fr_Laporan_Neraca_Judul.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Laporan_Neraca_Judul.setObjectName(_fromUtf8("fr_Laporan_Neraca_Judul"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.fr_Laporan_Neraca_Judul)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.lb_Laporan_Neraca_Judul = QtGui.QLabel(self.fr_Laporan_Neraca_Judul)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_Laporan_Neraca_Judul.sizePolicy().hasHeightForWidth())
        self.lb_Laporan_Neraca_Judul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setPointSize(18)
        self.lb_Laporan_Neraca_Judul.setFont(font)
        self.lb_Laporan_Neraca_Judul.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_Laporan_Neraca_Judul.setObjectName(_fromUtf8("lb_Laporan_Neraca_Judul"))
        self.horizontalLayout_15.addWidget(self.lb_Laporan_Neraca_Judul)
        self.gridLayout_3.addWidget(self.fr_Laporan_Neraca_Judul, 0, 0, 1, 1)
        self.fr_Laporan_Neraca_FA = QtGui.QFrame(self.st_Laporan_Neraca)
        self.fr_Laporan_Neraca_FA.setFrameShape(QtGui.QFrame.NoFrame)
        self.fr_Laporan_Neraca_FA.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Laporan_Neraca_FA.setObjectName(_fromUtf8("fr_Laporan_Neraca_FA"))
        self.gridLayout_15 = QtGui.QGridLayout(self.fr_Laporan_Neraca_FA)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.lb_Laporan_Neraca_ = QtGui.QLabel(self.fr_Laporan_Neraca_FA)
        self.lb_Laporan_Neraca_.setObjectName(_fromUtf8("lb_Laporan_Neraca_"))
        self.gridLayout_15.addWidget(self.lb_Laporan_Neraca_, 1, 1, 1, 1)
        self.dte_Laporan_Neraca_Dari = QtGui.QDateTimeEdit(self.fr_Laporan_Neraca_FA)
        self.dte_Laporan_Neraca_Dari.setObjectName(_fromUtf8("dte_Laporan_Neraca_Dari"))
        self.gridLayout_15.addWidget(self.dte_Laporan_Neraca_Dari, 1, 0, 1, 1)
        self.lb_Laporan_Neraca_Periode = QtGui.QLabel(self.fr_Laporan_Neraca_FA)
        self.lb_Laporan_Neraca_Periode.setObjectName(_fromUtf8("lb_Laporan_Neraca_Periode"))
        self.gridLayout_15.addWidget(self.lb_Laporan_Neraca_Periode, 0, 0, 1, 1)
        self.dte_Laporan_Neraca_Sampai = QtGui.QDateTimeEdit(self.fr_Laporan_Neraca_FA)
        self.dte_Laporan_Neraca_Sampai.setObjectName(_fromUtf8("dte_Laporan_Neraca_Sampai"))
        self.gridLayout_15.addWidget(self.dte_Laporan_Neraca_Sampai, 1, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem8, 1, 3, 1, 1)
        self.lb_Laporan_Neraca_Dari = QtGui.QLabel(self.fr_Laporan_Neraca_FA)
        self.lb_Laporan_Neraca_Dari.setObjectName(_fromUtf8("lb_Laporan_Neraca_Dari"))
        self.gridLayout_15.addWidget(self.lb_Laporan_Neraca_Dari, 2, 0, 1, 1)
        self.lb_Laporan_Neraca_Sampai = QtGui.QLabel(self.fr_Laporan_Neraca_FA)
        self.lb_Laporan_Neraca_Sampai.setObjectName(_fromUtf8("lb_Laporan_Neraca_Sampai"))
        self.gridLayout_15.addWidget(self.lb_Laporan_Neraca_Sampai, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.fr_Laporan_Neraca_FA, 1, 0, 1, 1)
        self.fr_Laporan_Neraca = QtGui.QFrame(self.st_Laporan_Neraca)
        self.fr_Laporan_Neraca.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_Laporan_Neraca.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Laporan_Neraca.setObjectName(_fromUtf8("fr_Laporan_Neraca"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.fr_Laporan_Neraca)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tb_Laporan_Neraca_Cetak = QtGui.QPushButton(self.fr_Laporan_Neraca)
        self.tb_Laporan_Neraca_Cetak.setObjectName(_fromUtf8("tb_Laporan_Neraca_Cetak"))
        self.horizontalLayout_3.addWidget(self.tb_Laporan_Neraca_Cetak)
        self.tb_Laporan_Neraca_Kembali = QtGui.QPushButton(self.fr_Laporan_Neraca)
        self.tb_Laporan_Neraca_Kembali.setObjectName(_fromUtf8("tb_Laporan_Neraca_Kembali"))
        self.horizontalLayout_3.addWidget(self.tb_Laporan_Neraca_Kembali)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.gridLayout_3.addWidget(self.fr_Laporan_Neraca, 2, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 262, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 3, 0, 1, 1)
        st_Laporan.addWidget(self.st_Laporan_Neraca)

        self.retranslateUi(st_Laporan)
        st_Laporan.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(st_Laporan)

    def retranslateUi(self, st_Laporan):
        st_Laporan.setWindowTitle(_translate("st_Laporan", "StackedWidget", None))
        self.gb_Menu_Laporan.setTitle(_translate("st_Laporan", "Laporan", None))
        self.tb_Menu_Laporan_KasHarian.setText(_translate("st_Laporan", "Laporan Kas Harian", None))
        self.tb_Menu_Laporan_LabaRugi.setText(_translate("st_Laporan", "Laporan Laba Rugi", None))
        self.tb_Menu_Laporan_Neraca.setText(_translate("st_Laporan", "Laporan Neraca", None))
        self.gb_Menu_SubLedger.setTitle(_translate("st_Laporan", "Subsidiary Ledger", None))
        self.tb_Menu_Laporan_HutangPiutangPerusahaan.setText(_translate("st_Laporan", "Laporan Hutang Piutang Perusahaan", None))
        self.tb_Menu_Laporan_JualBeliPerusahaan.setText(_translate("st_Laporan", "Laporan Jual Beli Perusahaan", None))
        self.lb_Laporan_KasHarian_Judul.setText(_translate("st_Laporan", "Laporan Kas Harian", None))
        self.lb_Laporan_KasHarian_.setText(_translate("st_Laporan", "-", None))
        self.lb_Laporan_KasHarian_Periode.setText(_translate("st_Laporan", "Periode", None))
        self.lb_Laporan_KasHarian_Dari.setText(_translate("st_Laporan", "dari", None))
        self.lb_Laporan_KasHarian_Sampai.setText(_translate("st_Laporan", "sampai", None))
        self.tb_Laporan_KasHarian_Cetak.setText(_translate("st_Laporan", "Cetak", None))
        self.tb_Laporan_KasHarian_Kembali.setText(_translate("st_Laporan", "Kembali", None))
        self.lb_Laporan_LabaRugi_Judul.setText(_translate("st_Laporan", "Laporan Laba Rugi", None))
        self.lb_Laporan_LabaRugi_.setText(_translate("st_Laporan", "-", None))
        self.lb_Laporan_LabaRugi_Periode.setText(_translate("st_Laporan", "Periode", None))
        self.lb_Laporan_LabaRugi_Dari.setText(_translate("st_Laporan", "dari", None))
        self.lb_Laporan_LabaRugi_Sampai.setText(_translate("st_Laporan", "sampai", None))
        self.tb_Laporan_LabaRugi_Cetak.setText(_translate("st_Laporan", "Cetak", None))
        self.tb_Laporan_LabaRugi_Kembali.setText(_translate("st_Laporan", "Kembali", None))
        self.lb_Laporan_Neraca_Judul.setText(_translate("st_Laporan", "Laporan Neraca", None))
        self.lb_Laporan_Neraca_.setText(_translate("st_Laporan", "-", None))
        self.lb_Laporan_Neraca_Periode.setText(_translate("st_Laporan", "Periode", None))
        self.lb_Laporan_Neraca_Dari.setText(_translate("st_Laporan", "dari", None))
        self.lb_Laporan_Neraca_Sampai.setText(_translate("st_Laporan", "sampai", None))
        self.tb_Laporan_Neraca_Cetak.setText(_translate("st_Laporan", "Cetak", None))
        self.tb_Laporan_Neraca_Kembali.setText(_translate("st_Laporan", "Kembali", None))

