# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kasbank/ui_kasbank.ui'
#
# Created: Sun Feb 15 00:59:59 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_st_KasBank(object):
    def setupUi(self, st_KasBank):
        st_KasBank.setObjectName(_fromUtf8("st_KasBank"))
        st_KasBank.resize(777, 584)
        st_KasBank.setStyleSheet(_fromUtf8("QFrame{border:0px;}\n"
"QTableWidget{border-width:1px;border-color:rgb(180, 200, 220);border-style:solid;border-radius:0px;}"))
        self.st_Menu = QtGui.QWidget()
        self.st_Menu.setObjectName(_fromUtf8("st_Menu"))
        self.igr_KasBank_Menu = QtGui.QGridLayout(self.st_Menu)
        self.igr_KasBank_Menu.setObjectName(_fromUtf8("igr_KasBank_Menu"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.igr_KasBank_Menu.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.igr_KasBank_Menu.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.igr_KasBank_Menu.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.igr_KasBank_Menu.addItem(spacerItem3, 1, 2, 1, 1)
        self.fr_Menu_Content = QtGui.QFrame(self.st_Menu)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_Menu_Content.sizePolicy().hasHeightForWidth())
        self.fr_Menu_Content.setSizePolicy(sizePolicy)
        self.fr_Menu_Content.setMinimumSize(QtCore.QSize(640, 480))
        self.fr_Menu_Content.setMaximumSize(QtCore.QSize(640, 480))
        self.fr_Menu_Content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_Menu_Content.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_Menu_Content.setObjectName(_fromUtf8("fr_Menu_Content"))
        self.tb_Menu_KasMasuk = QtGui.QPushButton(self.fr_Menu_Content)
        self.tb_Menu_KasMasuk.setGeometry(QtCore.QRect(220, 30, 101, 101))
        self.tb_Menu_KasMasuk.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tb_Menu_KasMasuk.setStyleSheet(_fromUtf8("QPushButton{\n"
"    background-color: rgb(248, 241, 243);\n"
"border-width:1px;\n"
"border-color:rgb(150, 137, 188);\n"
"border-style:outset;border-radius:8px;\n"
"font-family:Helvetica;\n"
"font-size:16pt;\n"
"font-weight:bold;\n"
"color:rgb(80,80,80);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(237, 244, 236);\n"
"color:rgb(0,0,0);\n"
" }"))
        self.tb_Menu_KasMasuk.setObjectName(_fromUtf8("tb_Menu_KasMasuk"))
        self.tb_Menu_KasKeluar = QtGui.QPushButton(self.fr_Menu_Content)
        self.tb_Menu_KasKeluar.setGeometry(QtCore.QRect(330, 30, 101, 101))
        self.tb_Menu_KasKeluar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tb_Menu_KasKeluar.setStyleSheet(_fromUtf8("QPushButton{\n"
"    background-color: rgb(248, 241, 243);\n"
"border-width:1px;\n"
"border-color:rgb(150, 137, 188);\n"
"border-style:outset;border-radius:8px;\n"
"font-family:Helvetica;\n"
"font-size:16pt;\n"
"font-weight:bold;\n"
"color:rgb(80,80,80);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(237, 244, 236);\n"
"color:rgb(0,0,0);\n"
" }"))
        self.tb_Menu_KasKeluar.setObjectName(_fromUtf8("tb_Menu_KasKeluar"))
        self.tb_Menu_BankMasuk = QtGui.QPushButton(self.fr_Menu_Content)
        self.tb_Menu_BankMasuk.setGeometry(QtCore.QRect(220, 140, 101, 101))
        self.tb_Menu_BankMasuk.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tb_Menu_BankMasuk.setStyleSheet(_fromUtf8("QPushButton{\n"
"    background-color: rgb(248, 241, 243);\n"
"border-width:1px;\n"
"border-color:rgb(150, 137, 188);\n"
"border-style:outset;border-radius:8px;\n"
"font-family:Helvetica;\n"
"font-size:16pt;\n"
"font-weight:bold;\n"
"color:rgb(80,80,80);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(237, 244, 236);\n"
"color:rgb(0,0,0);\n"
" }"))
        self.tb_Menu_BankMasuk.setObjectName(_fromUtf8("tb_Menu_BankMasuk"))
        self.tb_Menu_BankKeluar = QtGui.QPushButton(self.fr_Menu_Content)
        self.tb_Menu_BankKeluar.setGeometry(QtCore.QRect(330, 140, 101, 101))
        self.tb_Menu_BankKeluar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tb_Menu_BankKeluar.setStyleSheet(_fromUtf8("QPushButton{\n"
"    background-color: rgb(248, 241, 243);\n"
"border-width:1px;\n"
"border-color:rgb(150, 137, 188);\n"
"border-style:outset;border-radius:8px;\n"
"font-family:Helvetica;\n"
"font-size:16pt;\n"
"font-weight:bold;\n"
"color:rgb(80,80,80);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(237, 244, 236);\n"
"color:rgb(0,0,0);\n"
" }"))
        self.tb_Menu_BankKeluar.setObjectName(_fromUtf8("tb_Menu_BankKeluar"))
        self.igr_KasBank_Menu.addWidget(self.fr_Menu_Content, 1, 1, 1, 1)
        st_KasBank.addWidget(self.st_Menu)
        self.st_KasMasuk = QtGui.QWidget()
        self.st_KasMasuk.setObjectName(_fromUtf8("st_KasMasuk"))
        self.ivl_KasMasuk = QtGui.QVBoxLayout(self.st_KasMasuk)
        self.ivl_KasMasuk.setObjectName(_fromUtf8("ivl_KasMasuk"))
        self.fr_KasMasuk_t = QtGui.QFrame(self.st_KasMasuk)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasMasuk_t.sizePolicy().hasHeightForWidth())
        self.fr_KasMasuk_t.setSizePolicy(sizePolicy)
        self.fr_KasMasuk_t.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_KasMasuk_t.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_KasMasuk_t.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasMasuk_t.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasMasuk_t.setObjectName(_fromUtf8("fr_KasMasuk_t"))
        self.ihl_KasMasuk_t = QtGui.QHBoxLayout(self.fr_KasMasuk_t)
        self.ihl_KasMasuk_t.setObjectName(_fromUtf8("ihl_KasMasuk_t"))
        self.lb_KasMasuk_Judul = QtGui.QLabel(self.fr_KasMasuk_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lb_KasMasuk_Judul.sizePolicy().hasHeightForWidth())
        self.lb_KasMasuk_Judul.setSizePolicy(sizePolicy)
        self.lb_KasMasuk_Judul.setMinimumSize(QtCore.QSize(300, 0))
        self.lb_KasMasuk_Judul.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_KasMasuk_Judul.setFont(font)
        self.lb_KasMasuk_Judul.setObjectName(_fromUtf8("lb_KasMasuk_Judul"))
        self.ihl_KasMasuk_t.addWidget(self.lb_KasMasuk_Judul)
        spacerItem4 = QtGui.QSpacerItem(226, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_KasMasuk_t.addItem(spacerItem4)
        self.le_KasMasuk_Search = QtGui.QLineEdit(self.fr_KasMasuk_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.le_KasMasuk_Search.sizePolicy().hasHeightForWidth())
        self.le_KasMasuk_Search.setSizePolicy(sizePolicy)
        self.le_KasMasuk_Search.setMinimumSize(QtCore.QSize(200, 0))
        self.le_KasMasuk_Search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_KasMasuk_Search.setObjectName(_fromUtf8("le_KasMasuk_Search"))
        self.ihl_KasMasuk_t.addWidget(self.le_KasMasuk_Search)
        self.ivl_KasMasuk.addWidget(self.fr_KasMasuk_t)
        self.fr_KasMasuk_Content = QtGui.QFrame(self.st_KasMasuk)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasMasuk_Content.sizePolicy().hasHeightForWidth())
        self.fr_KasMasuk_Content.setSizePolicy(sizePolicy)
        self.fr_KasMasuk_Content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasMasuk_Content.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasMasuk_Content.setObjectName(_fromUtf8("fr_KasMasuk_Content"))
        self.ivl_KasMasuk_Content = QtGui.QVBoxLayout(self.fr_KasMasuk_Content)
        self.ivl_KasMasuk_Content.setObjectName(_fromUtf8("ivl_KasMasuk_Content"))
        self.tbl_KasMasuk = QtGui.QTableWidget(self.fr_KasMasuk_Content)
        self.tbl_KasMasuk.setObjectName(_fromUtf8("tbl_KasMasuk"))
        self.tbl_KasMasuk.setColumnCount(7)
        self.tbl_KasMasuk.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk.setHorizontalHeaderItem(6, item)
        self.ivl_KasMasuk_Content.addWidget(self.tbl_KasMasuk)
        self.ivl_KasMasuk.addWidget(self.fr_KasMasuk_Content)
        self.fr_KasMasuk_b = QtGui.QFrame(self.st_KasMasuk)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasMasuk_b.sizePolicy().hasHeightForWidth())
        self.fr_KasMasuk_b.setSizePolicy(sizePolicy)
        self.fr_KasMasuk_b.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_KasMasuk_b.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_KasMasuk_b.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasMasuk_b.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasMasuk_b.setObjectName(_fromUtf8("fr_KasMasuk_b"))
        self.ihl_KasMasuk_b = QtGui.QHBoxLayout(self.fr_KasMasuk_b)
        self.ihl_KasMasuk_b.setObjectName(_fromUtf8("ihl_KasMasuk_b"))
        self.tb_KasMasuk_Buka = QtGui.QPushButton(self.fr_KasMasuk_b)
        self.tb_KasMasuk_Buka.setObjectName(_fromUtf8("tb_KasMasuk_Buka"))
        self.ihl_KasMasuk_b.addWidget(self.tb_KasMasuk_Buka)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.ihl_KasMasuk_b.addItem(spacerItem5)
        self.tb_KasMasuk_Tambah = QtGui.QPushButton(self.fr_KasMasuk_b)
        self.tb_KasMasuk_Tambah.setObjectName(_fromUtf8("tb_KasMasuk_Tambah"))
        self.ihl_KasMasuk_b.addWidget(self.tb_KasMasuk_Tambah)
        self.tb_KasMasuk_Delete = QtGui.QPushButton(self.fr_KasMasuk_b)
        self.tb_KasMasuk_Delete.setObjectName(_fromUtf8("tb_KasMasuk_Delete"))
        self.ihl_KasMasuk_b.addWidget(self.tb_KasMasuk_Delete)
        spacerItem6 = QtGui.QSpacerItem(495, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_KasMasuk_b.addItem(spacerItem6)
        self.tb_KasMasuk_Tutup = QtGui.QPushButton(self.fr_KasMasuk_b)
        self.tb_KasMasuk_Tutup.setObjectName(_fromUtf8("tb_KasMasuk_Tutup"))
        self.ihl_KasMasuk_b.addWidget(self.tb_KasMasuk_Tutup)
        self.ivl_KasMasuk.addWidget(self.fr_KasMasuk_b)
        st_KasBank.addWidget(self.st_KasMasuk)
        self.st_KasMasuk_Tambah = QtGui.QWidget()
        self.st_KasMasuk_Tambah.setObjectName(_fromUtf8("st_KasMasuk_Tambah"))
        self.ivl_KasMasuk_Tambah = QtGui.QVBoxLayout(self.st_KasMasuk_Tambah)
        self.ivl_KasMasuk_Tambah.setObjectName(_fromUtf8("ivl_KasMasuk_Tambah"))
        self.fr_KasMasuk_Tambah_T = QtGui.QFrame(self.st_KasMasuk_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasMasuk_Tambah_T.sizePolicy().hasHeightForWidth())
        self.fr_KasMasuk_Tambah_T.setSizePolicy(sizePolicy)
        self.fr_KasMasuk_Tambah_T.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_KasMasuk_Tambah_T.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_KasMasuk_Tambah_T.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasMasuk_Tambah_T.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasMasuk_Tambah_T.setObjectName(_fromUtf8("fr_KasMasuk_Tambah_T"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.fr_KasMasuk_Tambah_T)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lb_KasMasuk_Judul_2 = QtGui.QLabel(self.fr_KasMasuk_Tambah_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lb_KasMasuk_Judul_2.sizePolicy().hasHeightForWidth())
        self.lb_KasMasuk_Judul_2.setSizePolicy(sizePolicy)
        self.lb_KasMasuk_Judul_2.setMinimumSize(QtCore.QSize(300, 0))
        self.lb_KasMasuk_Judul_2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_KasMasuk_Judul_2.setFont(font)
        self.lb_KasMasuk_Judul_2.setObjectName(_fromUtf8("lb_KasMasuk_Judul_2"))
        self.horizontalLayout.addWidget(self.lb_KasMasuk_Judul_2)
        spacerItem7 = QtGui.QSpacerItem(432, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.ivl_KasMasuk_Tambah.addWidget(self.fr_KasMasuk_Tambah_T)
        self.fr_KasMasuk_Tambah_Form = QtGui.QFrame(self.st_KasMasuk_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasMasuk_Tambah_Form.sizePolicy().hasHeightForWidth())
        self.fr_KasMasuk_Tambah_Form.setSizePolicy(sizePolicy)
        self.fr_KasMasuk_Tambah_Form.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fr_KasMasuk_Tambah_Form.setStyleSheet(_fromUtf8("QLineEdit,QPushButton{border-style:inset;border-width:1px;border-radius:2px;border-color:rgb(156, 156, 156);background-color:#ffffff;min-height:23px;}"))
        self.fr_KasMasuk_Tambah_Form.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasMasuk_Tambah_Form.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasMasuk_Tambah_Form.setObjectName(_fromUtf8("fr_KasMasuk_Tambah_Form"))
        self.gridLayout = QtGui.QGridLayout(self.fr_KasMasuk_Tambah_Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lb_KasMasuk_Tambah_Form_Tanggal = QtGui.QLabel(self.fr_KasMasuk_Tambah_Form)
        self.lb_KasMasuk_Tambah_Form_Tanggal.setObjectName(_fromUtf8("lb_KasMasuk_Tambah_Form_Tanggal"))
        self.gridLayout.addWidget(self.lb_KasMasuk_Tambah_Form_Tanggal, 3, 0, 1, 1)
        self.tb_KasMasuk_Tambah_Form_Penyetor = QtGui.QPushButton(self.fr_KasMasuk_Tambah_Form)
        self.tb_KasMasuk_Tambah_Form_Penyetor.setMinimumSize(QtCore.QSize(150, 25))
        self.tb_KasMasuk_Tambah_Form_Penyetor.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tb_KasMasuk_Tambah_Form_Penyetor.setObjectName(_fromUtf8("tb_KasMasuk_Tambah_Form_Penyetor"))
        self.gridLayout.addWidget(self.tb_KasMasuk_Tambah_Form_Penyetor, 2, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 6, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 6, 1, 1)
        self.tb_KasMasuk_Tambah_Form_NoAkun = QtGui.QPushButton(self.fr_KasMasuk_Tambah_Form)
        self.tb_KasMasuk_Tambah_Form_NoAkun.setMinimumSize(QtCore.QSize(150, 25))
        self.tb_KasMasuk_Tambah_Form_NoAkun.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tb_KasMasuk_Tambah_Form_NoAkun.setObjectName(_fromUtf8("tb_KasMasuk_Tambah_Form_NoAkun"))
        self.gridLayout.addWidget(self.tb_KasMasuk_Tambah_Form_NoAkun, 1, 2, 1, 1)
        self.le_KasMasuk_Tambah_Form_Catatan = QtGui.QLineEdit(self.fr_KasMasuk_Tambah_Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_KasMasuk_Tambah_Form_Catatan.sizePolicy().hasHeightForWidth())
        self.le_KasMasuk_Tambah_Form_Catatan.setSizePolicy(sizePolicy)
        self.le_KasMasuk_Tambah_Form_Catatan.setMaximumSize(QtCore.QSize(500, 16777215))
        self.le_KasMasuk_Tambah_Form_Catatan.setObjectName(_fromUtf8("le_KasMasuk_Tambah_Form_Catatan"))
        self.gridLayout.addWidget(self.le_KasMasuk_Tambah_Form_Catatan, 3, 5, 1, 2)
        self.lb_KasMasuk_Tambah_Form_NoAkun = QtGui.QLabel(self.fr_KasMasuk_Tambah_Form)
        self.lb_KasMasuk_Tambah_Form_NoAkun.setObjectName(_fromUtf8("lb_KasMasuk_Tambah_Form_NoAkun"))
        self.gridLayout.addWidget(self.lb_KasMasuk_Tambah_Form_NoAkun, 1, 0, 1, 1)
        self.lb_KasMasuk_Tambah_Form_Penyetor = QtGui.QLabel(self.fr_KasMasuk_Tambah_Form)
        self.lb_KasMasuk_Tambah_Form_Penyetor.setObjectName(_fromUtf8("lb_KasMasuk_Tambah_Form_Penyetor"))
        self.gridLayout.addWidget(self.lb_KasMasuk_Tambah_Form_Penyetor, 2, 0, 1, 1)
        self.lb_KasMasuk_Tambah_Form_Nilai = QtGui.QLabel(self.fr_KasMasuk_Tambah_Form)
        self.lb_KasMasuk_Tambah_Form_Nilai.setMinimumSize(QtCore.QSize(150, 0))
        self.lb_KasMasuk_Tambah_Form_Nilai.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lb_KasMasuk_Tambah_Form_Nilai.setObjectName(_fromUtf8("lb_KasMasuk_Tambah_Form_Nilai"))
        self.gridLayout.addWidget(self.lb_KasMasuk_Tambah_Form_Nilai, 2, 5, 1, 1)
        self.lb_KasMasuk_Tambah_Form_LabelNilai = QtGui.QLabel(self.fr_KasMasuk_Tambah_Form)
        self.lb_KasMasuk_Tambah_Form_LabelNilai.setObjectName(_fromUtf8("lb_KasMasuk_Tambah_Form_LabelNilai"))
        self.gridLayout.addWidget(self.lb_KasMasuk_Tambah_Form_LabelNilai, 2, 4, 1, 1)
        self.lb_KasMasuk_Tambah_Form_Catatan = QtGui.QLabel(self.fr_KasMasuk_Tambah_Form)
        self.lb_KasMasuk_Tambah_Form_Catatan.setObjectName(_fromUtf8("lb_KasMasuk_Tambah_Form_Catatan"))
        self.gridLayout.addWidget(self.lb_KasMasuk_Tambah_Form_Catatan, 3, 4, 1, 1)
        self.le_KasMasuk_Tambah_Form_Nomor = QtGui.QLineEdit(self.fr_KasMasuk_Tambah_Form)
        self.le_KasMasuk_Tambah_Form_Nomor.setMinimumSize(QtCore.QSize(150, 25))
        self.le_KasMasuk_Tambah_Form_Nomor.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_KasMasuk_Tambah_Form_Nomor.setObjectName(_fromUtf8("le_KasMasuk_Tambah_Form_Nomor"))
        self.gridLayout.addWidget(self.le_KasMasuk_Tambah_Form_Nomor, 1, 5, 1, 1)
        self.lb_KasMasuk_Tambah_Form_Nomor = QtGui.QLabel(self.fr_KasMasuk_Tambah_Form)
        self.lb_KasMasuk_Tambah_Form_Nomor.setObjectName(_fromUtf8("lb_KasMasuk_Tambah_Form_Nomor"))
        self.gridLayout.addWidget(self.lb_KasMasuk_Tambah_Form_Nomor, 1, 4, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 2, 3, 1, 1)
        self.dte_KasMasuk_Tambah_Form_Tanggal = QtGui.QDateTimeEdit(self.fr_KasMasuk_Tambah_Form)
        self.dte_KasMasuk_Tambah_Form_Tanggal.setCalendarPopup(True)
        self.dte_KasMasuk_Tambah_Form_Tanggal.setObjectName(_fromUtf8("dte_KasMasuk_Tambah_Form_Tanggal"))
        self.gridLayout.addWidget(self.dte_KasMasuk_Tambah_Form_Tanggal, 3, 2, 1, 1)
        self.ivl_KasMasuk_Tambah.addWidget(self.fr_KasMasuk_Tambah_Form)
        self.fr_KasMasuk_Tambah_Content = QtGui.QFrame(self.st_KasMasuk_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasMasuk_Tambah_Content.sizePolicy().hasHeightForWidth())
        self.fr_KasMasuk_Tambah_Content.setSizePolicy(sizePolicy)
        self.fr_KasMasuk_Tambah_Content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasMasuk_Tambah_Content.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasMasuk_Tambah_Content.setObjectName(_fromUtf8("fr_KasMasuk_Tambah_Content"))
        self.ivl_KasMasuk_Tambah_Content = QtGui.QVBoxLayout(self.fr_KasMasuk_Tambah_Content)
        self.ivl_KasMasuk_Tambah_Content.setObjectName(_fromUtf8("ivl_KasMasuk_Tambah_Content"))
        self.tbl_KasMasuk_Tambah = QtGui.QTableWidget(self.fr_KasMasuk_Tambah_Content)
        self.tbl_KasMasuk_Tambah.setObjectName(_fromUtf8("tbl_KasMasuk_Tambah"))
        self.tbl_KasMasuk_Tambah.setColumnCount(4)
        self.tbl_KasMasuk_Tambah.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk_Tambah.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk_Tambah.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk_Tambah.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasMasuk_Tambah.setHorizontalHeaderItem(3, item)
        self.ivl_KasMasuk_Tambah_Content.addWidget(self.tbl_KasMasuk_Tambah)
        self.ivl_KasMasuk_Tambah.addWidget(self.fr_KasMasuk_Tambah_Content)
        self.fr_KasMasuk_Tambah_B = QtGui.QFrame(self.st_KasMasuk_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasMasuk_Tambah_B.sizePolicy().hasHeightForWidth())
        self.fr_KasMasuk_Tambah_B.setSizePolicy(sizePolicy)
        self.fr_KasMasuk_Tambah_B.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_KasMasuk_Tambah_B.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_KasMasuk_Tambah_B.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasMasuk_Tambah_B.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasMasuk_Tambah_B.setObjectName(_fromUtf8("fr_KasMasuk_Tambah_B"))
        self.ihl_KasMasuk_Tambah_B = QtGui.QHBoxLayout(self.fr_KasMasuk_Tambah_B)
        self.ihl_KasMasuk_Tambah_B.setObjectName(_fromUtf8("ihl_KasMasuk_Tambah_B"))
        self.tb_KasMasuk_Tambah_TambahBaris = QtGui.QPushButton(self.fr_KasMasuk_Tambah_B)
        self.tb_KasMasuk_Tambah_TambahBaris.setObjectName(_fromUtf8("tb_KasMasuk_Tambah_TambahBaris"))
        self.ihl_KasMasuk_Tambah_B.addWidget(self.tb_KasMasuk_Tambah_TambahBaris)
        self.tb_KasMasuk_Tambah_HapusBaris = QtGui.QPushButton(self.fr_KasMasuk_Tambah_B)
        self.tb_KasMasuk_Tambah_HapusBaris.setObjectName(_fromUtf8("tb_KasMasuk_Tambah_HapusBaris"))
        self.ihl_KasMasuk_Tambah_B.addWidget(self.tb_KasMasuk_Tambah_HapusBaris)
        spacerItem11 = QtGui.QSpacerItem(374, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_KasMasuk_Tambah_B.addItem(spacerItem11)
        self.tb_KasMasuk_Tambah_Simpan = QtGui.QPushButton(self.fr_KasMasuk_Tambah_B)
        self.tb_KasMasuk_Tambah_Simpan.setObjectName(_fromUtf8("tb_KasMasuk_Tambah_Simpan"))
        self.ihl_KasMasuk_Tambah_B.addWidget(self.tb_KasMasuk_Tambah_Simpan)
        self.tb_KasMasuk_Tambah_Cetak = QtGui.QPushButton(self.fr_KasMasuk_Tambah_B)
        self.tb_KasMasuk_Tambah_Cetak.setObjectName(_fromUtf8("tb_KasMasuk_Tambah_Cetak"))
        self.ihl_KasMasuk_Tambah_B.addWidget(self.tb_KasMasuk_Tambah_Cetak)
        self.tb_KasMasuk_Tambah_Batal = QtGui.QPushButton(self.fr_KasMasuk_Tambah_B)
        self.tb_KasMasuk_Tambah_Batal.setObjectName(_fromUtf8("tb_KasMasuk_Tambah_Batal"))
        self.ihl_KasMasuk_Tambah_B.addWidget(self.tb_KasMasuk_Tambah_Batal)
        self.ivl_KasMasuk_Tambah.addWidget(self.fr_KasMasuk_Tambah_B)
        st_KasBank.addWidget(self.st_KasMasuk_Tambah)
        self.st_KasKeluar = QtGui.QWidget()
        self.st_KasKeluar.setObjectName(_fromUtf8("st_KasKeluar"))
        self.ivl_KasKeluar = QtGui.QVBoxLayout(self.st_KasKeluar)
        self.ivl_KasKeluar.setObjectName(_fromUtf8("ivl_KasKeluar"))
        self.fr_KasKeluar_t = QtGui.QFrame(self.st_KasKeluar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasKeluar_t.sizePolicy().hasHeightForWidth())
        self.fr_KasKeluar_t.setSizePolicy(sizePolicy)
        self.fr_KasKeluar_t.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_KasKeluar_t.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_KasKeluar_t.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasKeluar_t.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasKeluar_t.setObjectName(_fromUtf8("fr_KasKeluar_t"))
        self.ihl_KasKeluar_t = QtGui.QHBoxLayout(self.fr_KasKeluar_t)
        self.ihl_KasKeluar_t.setObjectName(_fromUtf8("ihl_KasKeluar_t"))
        self.lb_KasKeluar_Judul = QtGui.QLabel(self.fr_KasKeluar_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lb_KasKeluar_Judul.sizePolicy().hasHeightForWidth())
        self.lb_KasKeluar_Judul.setSizePolicy(sizePolicy)
        self.lb_KasKeluar_Judul.setMinimumSize(QtCore.QSize(300, 0))
        self.lb_KasKeluar_Judul.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_KasKeluar_Judul.setFont(font)
        self.lb_KasKeluar_Judul.setObjectName(_fromUtf8("lb_KasKeluar_Judul"))
        self.ihl_KasKeluar_t.addWidget(self.lb_KasKeluar_Judul)
        spacerItem12 = QtGui.QSpacerItem(226, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_KasKeluar_t.addItem(spacerItem12)
        self.le_KasKeluar_Search = QtGui.QLineEdit(self.fr_KasKeluar_t)
        self.le_KasKeluar_Search.setMinimumSize(QtCore.QSize(200, 0))
        self.le_KasKeluar_Search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_KasKeluar_Search.setObjectName(_fromUtf8("le_KasKeluar_Search"))
        self.ihl_KasKeluar_t.addWidget(self.le_KasKeluar_Search)
        self.ivl_KasKeluar.addWidget(self.fr_KasKeluar_t)
        self.fr_KasKeluar_Content = QtGui.QFrame(self.st_KasKeluar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasKeluar_Content.sizePolicy().hasHeightForWidth())
        self.fr_KasKeluar_Content.setSizePolicy(sizePolicy)
        self.fr_KasKeluar_Content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasKeluar_Content.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasKeluar_Content.setObjectName(_fromUtf8("fr_KasKeluar_Content"))
        self.ivl_KasKeluar_Content = QtGui.QVBoxLayout(self.fr_KasKeluar_Content)
        self.ivl_KasKeluar_Content.setObjectName(_fromUtf8("ivl_KasKeluar_Content"))
        self.tbl_KasKeluar = QtGui.QTableWidget(self.fr_KasKeluar_Content)
        self.tbl_KasKeluar.setObjectName(_fromUtf8("tbl_KasKeluar"))
        self.tbl_KasKeluar.setColumnCount(7)
        self.tbl_KasKeluar.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar.setHorizontalHeaderItem(6, item)
        self.ivl_KasKeluar_Content.addWidget(self.tbl_KasKeluar)
        self.ivl_KasKeluar.addWidget(self.fr_KasKeluar_Content)
        self.fr_KasKeluar_b = QtGui.QFrame(self.st_KasKeluar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasKeluar_b.sizePolicy().hasHeightForWidth())
        self.fr_KasKeluar_b.setSizePolicy(sizePolicy)
        self.fr_KasKeluar_b.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_KasKeluar_b.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_KasKeluar_b.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasKeluar_b.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasKeluar_b.setObjectName(_fromUtf8("fr_KasKeluar_b"))
        self.ihl_KasKeluar_b = QtGui.QHBoxLayout(self.fr_KasKeluar_b)
        self.ihl_KasKeluar_b.setObjectName(_fromUtf8("ihl_KasKeluar_b"))
        self.tb_KasKeluar_Buka = QtGui.QPushButton(self.fr_KasKeluar_b)
        self.tb_KasKeluar_Buka.setObjectName(_fromUtf8("tb_KasKeluar_Buka"))
        self.ihl_KasKeluar_b.addWidget(self.tb_KasKeluar_Buka)
        spacerItem13 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.ihl_KasKeluar_b.addItem(spacerItem13)
        self.tb_KasKeluar_Tambah = QtGui.QPushButton(self.fr_KasKeluar_b)
        self.tb_KasKeluar_Tambah.setObjectName(_fromUtf8("tb_KasKeluar_Tambah"))
        self.ihl_KasKeluar_b.addWidget(self.tb_KasKeluar_Tambah)
        self.tb_KasKeluar_Delete = QtGui.QPushButton(self.fr_KasKeluar_b)
        self.tb_KasKeluar_Delete.setObjectName(_fromUtf8("tb_KasKeluar_Delete"))
        self.ihl_KasKeluar_b.addWidget(self.tb_KasKeluar_Delete)
        spacerItem14 = QtGui.QSpacerItem(495, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_KasKeluar_b.addItem(spacerItem14)
        self.tb_KasKeluar_Tutup = QtGui.QPushButton(self.fr_KasKeluar_b)
        self.tb_KasKeluar_Tutup.setObjectName(_fromUtf8("tb_KasKeluar_Tutup"))
        self.ihl_KasKeluar_b.addWidget(self.tb_KasKeluar_Tutup)
        self.ivl_KasKeluar.addWidget(self.fr_KasKeluar_b)
        st_KasBank.addWidget(self.st_KasKeluar)
        self.st_KasKeluar_Tambah = QtGui.QWidget()
        self.st_KasKeluar_Tambah.setObjectName(_fromUtf8("st_KasKeluar_Tambah"))
        self.ivl_KasKeluar_Tambah = QtGui.QVBoxLayout(self.st_KasKeluar_Tambah)
        self.ivl_KasKeluar_Tambah.setObjectName(_fromUtf8("ivl_KasKeluar_Tambah"))
        self.fr_KasKeluar_Tambah_T = QtGui.QFrame(self.st_KasKeluar_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasKeluar_Tambah_T.sizePolicy().hasHeightForWidth())
        self.fr_KasKeluar_Tambah_T.setSizePolicy(sizePolicy)
        self.fr_KasKeluar_Tambah_T.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_KasKeluar_Tambah_T.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_KasKeluar_Tambah_T.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasKeluar_Tambah_T.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasKeluar_Tambah_T.setObjectName(_fromUtf8("fr_KasKeluar_Tambah_T"))
        self.horizontalLayout1 = QtGui.QHBoxLayout(self.fr_KasKeluar_Tambah_T)
        self.horizontalLayout1.setObjectName(_fromUtf8("horizontalLayout1"))
        self.lb_KasKeluar_Judul_3 = QtGui.QLabel(self.fr_KasKeluar_Tambah_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lb_KasKeluar_Judul_3.sizePolicy().hasHeightForWidth())
        self.lb_KasKeluar_Judul_3.setSizePolicy(sizePolicy)
        self.lb_KasKeluar_Judul_3.setMinimumSize(QtCore.QSize(300, 0))
        self.lb_KasKeluar_Judul_3.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_KasKeluar_Judul_3.setFont(font)
        self.lb_KasKeluar_Judul_3.setObjectName(_fromUtf8("lb_KasKeluar_Judul_3"))
        self.horizontalLayout1.addWidget(self.lb_KasKeluar_Judul_3)
        spacerItem15 = QtGui.QSpacerItem(432, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout1.addItem(spacerItem15)
        self.ivl_KasKeluar_Tambah.addWidget(self.fr_KasKeluar_Tambah_T)
        self.fr_KasKeluar_Tambah_Form = QtGui.QFrame(self.st_KasKeluar_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasKeluar_Tambah_Form.sizePolicy().hasHeightForWidth())
        self.fr_KasKeluar_Tambah_Form.setSizePolicy(sizePolicy)
        self.fr_KasKeluar_Tambah_Form.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fr_KasKeluar_Tambah_Form.setStyleSheet(_fromUtf8("QLineEdit,QPushButton{border-style:inset;border-width:1px;border-radius:2px;border-color:rgb(156, 156, 156);background-color:#ffffff;min-height:23px;}"))
        self.fr_KasKeluar_Tambah_Form.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasKeluar_Tambah_Form.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasKeluar_Tambah_Form.setObjectName(_fromUtf8("fr_KasKeluar_Tambah_Form"))
        self.gridLayout1 = QtGui.QGridLayout(self.fr_KasKeluar_Tambah_Form)
        self.gridLayout1.setObjectName(_fromUtf8("gridLayout1"))
        self.lb_KasKeluar_Tambah_Form_Tanggal = QtGui.QLabel(self.fr_KasKeluar_Tambah_Form)
        self.lb_KasKeluar_Tambah_Form_Tanggal.setObjectName(_fromUtf8("lb_KasKeluar_Tambah_Form_Tanggal"))
        self.gridLayout1.addWidget(self.lb_KasKeluar_Tambah_Form_Tanggal, 3, 0, 1, 1)
        self.tb_KasKeluar_Tambah_Form_Penerima = QtGui.QPushButton(self.fr_KasKeluar_Tambah_Form)
        self.tb_KasKeluar_Tambah_Form_Penerima.setMinimumSize(QtCore.QSize(150, 25))
        self.tb_KasKeluar_Tambah_Form_Penerima.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tb_KasKeluar_Tambah_Form_Penerima.setObjectName(_fromUtf8("tb_KasKeluar_Tambah_Form_Penerima"))
        self.gridLayout1.addWidget(self.tb_KasKeluar_Tambah_Form_Penerima, 2, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout1.addItem(spacerItem16, 2, 6, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout1.addItem(spacerItem17, 1, 6, 1, 1)
        self.tb_KasKeluar_Tambah_Form_NoAkun = QtGui.QPushButton(self.fr_KasKeluar_Tambah_Form)
        self.tb_KasKeluar_Tambah_Form_NoAkun.setMinimumSize(QtCore.QSize(150, 25))
        self.tb_KasKeluar_Tambah_Form_NoAkun.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tb_KasKeluar_Tambah_Form_NoAkun.setObjectName(_fromUtf8("tb_KasKeluar_Tambah_Form_NoAkun"))
        self.gridLayout1.addWidget(self.tb_KasKeluar_Tambah_Form_NoAkun, 1, 2, 1, 1)
        self.le_KasKeluar_Tambah_Form_Catatan = QtGui.QLineEdit(self.fr_KasKeluar_Tambah_Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_KasKeluar_Tambah_Form_Catatan.sizePolicy().hasHeightForWidth())
        self.le_KasKeluar_Tambah_Form_Catatan.setSizePolicy(sizePolicy)
        self.le_KasKeluar_Tambah_Form_Catatan.setMaximumSize(QtCore.QSize(500, 16777215))
        self.le_KasKeluar_Tambah_Form_Catatan.setObjectName(_fromUtf8("le_KasKeluar_Tambah_Form_Catatan"))
        self.gridLayout1.addWidget(self.le_KasKeluar_Tambah_Form_Catatan, 3, 5, 1, 2)
        self.lb_KasKeluar_Tambah_Form_NoAkun = QtGui.QLabel(self.fr_KasKeluar_Tambah_Form)
        self.lb_KasKeluar_Tambah_Form_NoAkun.setObjectName(_fromUtf8("lb_KasKeluar_Tambah_Form_NoAkun"))
        self.gridLayout1.addWidget(self.lb_KasKeluar_Tambah_Form_NoAkun, 1, 0, 1, 1)
        self.lb_KasKeluar_Tambah_Form_Penerima = QtGui.QLabel(self.fr_KasKeluar_Tambah_Form)
        self.lb_KasKeluar_Tambah_Form_Penerima.setObjectName(_fromUtf8("lb_KasKeluar_Tambah_Form_Penerima"))
        self.gridLayout1.addWidget(self.lb_KasKeluar_Tambah_Form_Penerima, 2, 0, 1, 1)
        self.lb_KasKeluar_Tambah_Form_Nilai = QtGui.QLabel(self.fr_KasKeluar_Tambah_Form)
        self.lb_KasKeluar_Tambah_Form_Nilai.setMinimumSize(QtCore.QSize(150, 0))
        self.lb_KasKeluar_Tambah_Form_Nilai.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lb_KasKeluar_Tambah_Form_Nilai.setObjectName(_fromUtf8("lb_KasKeluar_Tambah_Form_Nilai"))
        self.gridLayout1.addWidget(self.lb_KasKeluar_Tambah_Form_Nilai, 2, 5, 1, 1)
        self.lb_KasKeluar_Tambah_Form_LabelNilai = QtGui.QLabel(self.fr_KasKeluar_Tambah_Form)
        self.lb_KasKeluar_Tambah_Form_LabelNilai.setObjectName(_fromUtf8("lb_KasKeluar_Tambah_Form_LabelNilai"))
        self.gridLayout1.addWidget(self.lb_KasKeluar_Tambah_Form_LabelNilai, 2, 4, 1, 1)
        self.lb_KasKeluar_Tambah_Form_Catatan = QtGui.QLabel(self.fr_KasKeluar_Tambah_Form)
        self.lb_KasKeluar_Tambah_Form_Catatan.setObjectName(_fromUtf8("lb_KasKeluar_Tambah_Form_Catatan"))
        self.gridLayout1.addWidget(self.lb_KasKeluar_Tambah_Form_Catatan, 3, 4, 1, 1)
        self.le_KasKeluar_Tambah_Form_Nomor = QtGui.QLineEdit(self.fr_KasKeluar_Tambah_Form)
        self.le_KasKeluar_Tambah_Form_Nomor.setMinimumSize(QtCore.QSize(150, 25))
        self.le_KasKeluar_Tambah_Form_Nomor.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_KasKeluar_Tambah_Form_Nomor.setObjectName(_fromUtf8("le_KasKeluar_Tambah_Form_Nomor"))
        self.gridLayout1.addWidget(self.le_KasKeluar_Tambah_Form_Nomor, 1, 5, 1, 1)
        self.lb_KasKeluar_Tambah_Form_Nomor = QtGui.QLabel(self.fr_KasKeluar_Tambah_Form)
        self.lb_KasKeluar_Tambah_Form_Nomor.setObjectName(_fromUtf8("lb_KasKeluar_Tambah_Form_Nomor"))
        self.gridLayout1.addWidget(self.lb_KasKeluar_Tambah_Form_Nomor, 1, 4, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout1.addItem(spacerItem18, 2, 3, 1, 1)
        self.dte_KasKeluar_Tambah_Form_Tanggal = QtGui.QDateTimeEdit(self.fr_KasKeluar_Tambah_Form)
        self.dte_KasKeluar_Tambah_Form_Tanggal.setCalendarPopup(True)
        self.dte_KasKeluar_Tambah_Form_Tanggal.setObjectName(_fromUtf8("dte_KasKeluar_Tambah_Form_Tanggal"))
        self.gridLayout1.addWidget(self.dte_KasKeluar_Tambah_Form_Tanggal, 3, 2, 1, 1)
        self.ivl_KasKeluar_Tambah.addWidget(self.fr_KasKeluar_Tambah_Form)
        self.fr_KasKeluar_Tambah_Content = QtGui.QFrame(self.st_KasKeluar_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasKeluar_Tambah_Content.sizePolicy().hasHeightForWidth())
        self.fr_KasKeluar_Tambah_Content.setSizePolicy(sizePolicy)
        self.fr_KasKeluar_Tambah_Content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasKeluar_Tambah_Content.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasKeluar_Tambah_Content.setObjectName(_fromUtf8("fr_KasKeluar_Tambah_Content"))
        self.ivl_KasKeluar_Tambah_Content = QtGui.QVBoxLayout(self.fr_KasKeluar_Tambah_Content)
        self.ivl_KasKeluar_Tambah_Content.setObjectName(_fromUtf8("ivl_KasKeluar_Tambah_Content"))
        self.tbl_KasKeluar_Tambah = QtGui.QTableWidget(self.fr_KasKeluar_Tambah_Content)
        self.tbl_KasKeluar_Tambah.setObjectName(_fromUtf8("tbl_KasKeluar_Tambah"))
        self.tbl_KasKeluar_Tambah.setColumnCount(4)
        self.tbl_KasKeluar_Tambah.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar_Tambah.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar_Tambah.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar_Tambah.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_KasKeluar_Tambah.setHorizontalHeaderItem(3, item)
        self.ivl_KasKeluar_Tambah_Content.addWidget(self.tbl_KasKeluar_Tambah)
        self.ivl_KasKeluar_Tambah.addWidget(self.fr_KasKeluar_Tambah_Content)
        self.fr_KasKeluar_Tambah_B = QtGui.QFrame(self.st_KasKeluar_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_KasKeluar_Tambah_B.sizePolicy().hasHeightForWidth())
        self.fr_KasKeluar_Tambah_B.setSizePolicy(sizePolicy)
        self.fr_KasKeluar_Tambah_B.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_KasKeluar_Tambah_B.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_KasKeluar_Tambah_B.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_KasKeluar_Tambah_B.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_KasKeluar_Tambah_B.setObjectName(_fromUtf8("fr_KasKeluar_Tambah_B"))
        self.ihl_KasKeluar_Tambah_B = QtGui.QHBoxLayout(self.fr_KasKeluar_Tambah_B)
        self.ihl_KasKeluar_Tambah_B.setObjectName(_fromUtf8("ihl_KasKeluar_Tambah_B"))
        self.tb_KasKeluar_Tambah_TambahBaris = QtGui.QPushButton(self.fr_KasKeluar_Tambah_B)
        self.tb_KasKeluar_Tambah_TambahBaris.setObjectName(_fromUtf8("tb_KasKeluar_Tambah_TambahBaris"))
        self.ihl_KasKeluar_Tambah_B.addWidget(self.tb_KasKeluar_Tambah_TambahBaris)
        self.tb_KasKeluar_Tambah_HapusBaris = QtGui.QPushButton(self.fr_KasKeluar_Tambah_B)
        self.tb_KasKeluar_Tambah_HapusBaris.setObjectName(_fromUtf8("tb_KasKeluar_Tambah_HapusBaris"))
        self.ihl_KasKeluar_Tambah_B.addWidget(self.tb_KasKeluar_Tambah_HapusBaris)
        spacerItem19 = QtGui.QSpacerItem(374, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_KasKeluar_Tambah_B.addItem(spacerItem19)
        self.tb_KasKeluar_Tambah_Simpan = QtGui.QPushButton(self.fr_KasKeluar_Tambah_B)
        self.tb_KasKeluar_Tambah_Simpan.setObjectName(_fromUtf8("tb_KasKeluar_Tambah_Simpan"))
        self.ihl_KasKeluar_Tambah_B.addWidget(self.tb_KasKeluar_Tambah_Simpan)
        self.tb_KasKeluar_Tambah_Cetak = QtGui.QPushButton(self.fr_KasKeluar_Tambah_B)
        self.tb_KasKeluar_Tambah_Cetak.setObjectName(_fromUtf8("tb_KasKeluar_Tambah_Cetak"))
        self.ihl_KasKeluar_Tambah_B.addWidget(self.tb_KasKeluar_Tambah_Cetak)
        self.tb_KasKeluar_Tambah_Batal = QtGui.QPushButton(self.fr_KasKeluar_Tambah_B)
        self.tb_KasKeluar_Tambah_Batal.setObjectName(_fromUtf8("tb_KasKeluar_Tambah_Batal"))
        self.ihl_KasKeluar_Tambah_B.addWidget(self.tb_KasKeluar_Tambah_Batal)
        self.ivl_KasKeluar_Tambah.addWidget(self.fr_KasKeluar_Tambah_B)
        st_KasBank.addWidget(self.st_KasKeluar_Tambah)
        self.st_BankMasuk = QtGui.QWidget()
        self.st_BankMasuk.setObjectName(_fromUtf8("st_BankMasuk"))
        self.ivl_BankMasuk = QtGui.QVBoxLayout(self.st_BankMasuk)
        self.ivl_BankMasuk.setObjectName(_fromUtf8("ivl_BankMasuk"))
        self.fr_BankMasuk_t = QtGui.QFrame(self.st_BankMasuk)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankMasuk_t.sizePolicy().hasHeightForWidth())
        self.fr_BankMasuk_t.setSizePolicy(sizePolicy)
        self.fr_BankMasuk_t.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_BankMasuk_t.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_BankMasuk_t.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankMasuk_t.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankMasuk_t.setObjectName(_fromUtf8("fr_BankMasuk_t"))
        self.ihl_BankMasuk_t = QtGui.QHBoxLayout(self.fr_BankMasuk_t)
        self.ihl_BankMasuk_t.setObjectName(_fromUtf8("ihl_BankMasuk_t"))
        self.lb_BankMasuk_Judul = QtGui.QLabel(self.fr_BankMasuk_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lb_BankMasuk_Judul.sizePolicy().hasHeightForWidth())
        self.lb_BankMasuk_Judul.setSizePolicy(sizePolicy)
        self.lb_BankMasuk_Judul.setMinimumSize(QtCore.QSize(300, 0))
        self.lb_BankMasuk_Judul.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_BankMasuk_Judul.setFont(font)
        self.lb_BankMasuk_Judul.setObjectName(_fromUtf8("lb_BankMasuk_Judul"))
        self.ihl_BankMasuk_t.addWidget(self.lb_BankMasuk_Judul)
        spacerItem20 = QtGui.QSpacerItem(226, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_BankMasuk_t.addItem(spacerItem20)
        self.le_BankMasuk_Search = QtGui.QLineEdit(self.fr_BankMasuk_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.le_BankMasuk_Search.sizePolicy().hasHeightForWidth())
        self.le_BankMasuk_Search.setSizePolicy(sizePolicy)
        self.le_BankMasuk_Search.setMinimumSize(QtCore.QSize(200, 0))
        self.le_BankMasuk_Search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_BankMasuk_Search.setObjectName(_fromUtf8("le_BankMasuk_Search"))
        self.ihl_BankMasuk_t.addWidget(self.le_BankMasuk_Search)
        self.ivl_BankMasuk.addWidget(self.fr_BankMasuk_t)
        self.fr_BankMasuk_Content = QtGui.QFrame(self.st_BankMasuk)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankMasuk_Content.sizePolicy().hasHeightForWidth())
        self.fr_BankMasuk_Content.setSizePolicy(sizePolicy)
        self.fr_BankMasuk_Content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankMasuk_Content.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankMasuk_Content.setObjectName(_fromUtf8("fr_BankMasuk_Content"))
        self.ivl_BankMasuk_Content = QtGui.QVBoxLayout(self.fr_BankMasuk_Content)
        self.ivl_BankMasuk_Content.setObjectName(_fromUtf8("ivl_BankMasuk_Content"))
        self.tbl_BankMasuk = QtGui.QTableWidget(self.fr_BankMasuk_Content)
        self.tbl_BankMasuk.setObjectName(_fromUtf8("tbl_BankMasuk"))
        self.tbl_BankMasuk.setColumnCount(7)
        self.tbl_BankMasuk.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk.setHorizontalHeaderItem(6, item)
        self.ivl_BankMasuk_Content.addWidget(self.tbl_BankMasuk)
        self.ivl_BankMasuk.addWidget(self.fr_BankMasuk_Content)
        self.fr_BankMasuk_b = QtGui.QFrame(self.st_BankMasuk)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankMasuk_b.sizePolicy().hasHeightForWidth())
        self.fr_BankMasuk_b.setSizePolicy(sizePolicy)
        self.fr_BankMasuk_b.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_BankMasuk_b.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_BankMasuk_b.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankMasuk_b.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankMasuk_b.setObjectName(_fromUtf8("fr_BankMasuk_b"))
        self.ihl_BankMasuk_b = QtGui.QHBoxLayout(self.fr_BankMasuk_b)
        self.ihl_BankMasuk_b.setObjectName(_fromUtf8("ihl_BankMasuk_b"))
        self.tb_BankMasuk_Buka = QtGui.QPushButton(self.fr_BankMasuk_b)
        self.tb_BankMasuk_Buka.setObjectName(_fromUtf8("tb_BankMasuk_Buka"))
        self.ihl_BankMasuk_b.addWidget(self.tb_BankMasuk_Buka)
        spacerItem21 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.ihl_BankMasuk_b.addItem(spacerItem21)
        self.tb_BankMasuk_Tambah = QtGui.QPushButton(self.fr_BankMasuk_b)
        self.tb_BankMasuk_Tambah.setObjectName(_fromUtf8("tb_BankMasuk_Tambah"))
        self.ihl_BankMasuk_b.addWidget(self.tb_BankMasuk_Tambah)
        self.tb_BankMasuk_Delete = QtGui.QPushButton(self.fr_BankMasuk_b)
        self.tb_BankMasuk_Delete.setObjectName(_fromUtf8("tb_BankMasuk_Delete"))
        self.ihl_BankMasuk_b.addWidget(self.tb_BankMasuk_Delete)
        spacerItem22 = QtGui.QSpacerItem(495, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_BankMasuk_b.addItem(spacerItem22)
        self.tb_BankMasuk_Tutup = QtGui.QPushButton(self.fr_BankMasuk_b)
        self.tb_BankMasuk_Tutup.setObjectName(_fromUtf8("tb_BankMasuk_Tutup"))
        self.ihl_BankMasuk_b.addWidget(self.tb_BankMasuk_Tutup)
        self.ivl_BankMasuk.addWidget(self.fr_BankMasuk_b)
        st_KasBank.addWidget(self.st_BankMasuk)
        self.st_BankMasuk_Tambah = QtGui.QWidget()
        self.st_BankMasuk_Tambah.setObjectName(_fromUtf8("st_BankMasuk_Tambah"))
        self.ivl_BankMasuk_Tambah = QtGui.QVBoxLayout(self.st_BankMasuk_Tambah)
        self.ivl_BankMasuk_Tambah.setObjectName(_fromUtf8("ivl_BankMasuk_Tambah"))
        self.fr_BankMasuk_Tambah_T = QtGui.QFrame(self.st_BankMasuk_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankMasuk_Tambah_T.sizePolicy().hasHeightForWidth())
        self.fr_BankMasuk_Tambah_T.setSizePolicy(sizePolicy)
        self.fr_BankMasuk_Tambah_T.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_BankMasuk_Tambah_T.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_BankMasuk_Tambah_T.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankMasuk_Tambah_T.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankMasuk_Tambah_T.setObjectName(_fromUtf8("fr_BankMasuk_Tambah_T"))
        self.horizontalLayout2 = QtGui.QHBoxLayout(self.fr_BankMasuk_Tambah_T)
        self.horizontalLayout2.setObjectName(_fromUtf8("horizontalLayout2"))
        self.lb_BankMasuk_Judul_2 = QtGui.QLabel(self.fr_BankMasuk_Tambah_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lb_BankMasuk_Judul_2.sizePolicy().hasHeightForWidth())
        self.lb_BankMasuk_Judul_2.setSizePolicy(sizePolicy)
        self.lb_BankMasuk_Judul_2.setMinimumSize(QtCore.QSize(300, 0))
        self.lb_BankMasuk_Judul_2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_BankMasuk_Judul_2.setFont(font)
        self.lb_BankMasuk_Judul_2.setObjectName(_fromUtf8("lb_BankMasuk_Judul_2"))
        self.horizontalLayout2.addWidget(self.lb_BankMasuk_Judul_2)
        spacerItem23 = QtGui.QSpacerItem(432, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout2.addItem(spacerItem23)
        self.ivl_BankMasuk_Tambah.addWidget(self.fr_BankMasuk_Tambah_T)
        self.fr_BankMasuk_Tambah_Form = QtGui.QFrame(self.st_BankMasuk_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankMasuk_Tambah_Form.sizePolicy().hasHeightForWidth())
        self.fr_BankMasuk_Tambah_Form.setSizePolicy(sizePolicy)
        self.fr_BankMasuk_Tambah_Form.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fr_BankMasuk_Tambah_Form.setStyleSheet(_fromUtf8("QLineEdit,QPushButton{border-style:inset;border-width:1px;border-radius:2px;border-color:rgb(156, 156, 156);background-color:#ffffff;min-height:23px;}"))
        self.fr_BankMasuk_Tambah_Form.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankMasuk_Tambah_Form.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankMasuk_Tambah_Form.setObjectName(_fromUtf8("fr_BankMasuk_Tambah_Form"))
        self.gridLayout2 = QtGui.QGridLayout(self.fr_BankMasuk_Tambah_Form)
        self.gridLayout2.setObjectName(_fromUtf8("gridLayout2"))
        self.lb_BankMasuk_Tambah_Form_Tanggal = QtGui.QLabel(self.fr_BankMasuk_Tambah_Form)
        self.lb_BankMasuk_Tambah_Form_Tanggal.setObjectName(_fromUtf8("lb_BankMasuk_Tambah_Form_Tanggal"))
        self.gridLayout2.addWidget(self.lb_BankMasuk_Tambah_Form_Tanggal, 3, 0, 1, 1)
        self.tb_BankMasuk_Tambah_Form_Penyetor = QtGui.QPushButton(self.fr_BankMasuk_Tambah_Form)
        self.tb_BankMasuk_Tambah_Form_Penyetor.setMinimumSize(QtCore.QSize(150, 25))
        self.tb_BankMasuk_Tambah_Form_Penyetor.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tb_BankMasuk_Tambah_Form_Penyetor.setObjectName(_fromUtf8("tb_BankMasuk_Tambah_Form_Penyetor"))
        self.gridLayout2.addWidget(self.tb_BankMasuk_Tambah_Form_Penyetor, 2, 2, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout2.addItem(spacerItem24, 2, 6, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout2.addItem(spacerItem25, 1, 6, 1, 1)
        self.tb_BankMasuk_Tambah_Form_NoAkun = QtGui.QPushButton(self.fr_BankMasuk_Tambah_Form)
        self.tb_BankMasuk_Tambah_Form_NoAkun.setMinimumSize(QtCore.QSize(150, 25))
        self.tb_BankMasuk_Tambah_Form_NoAkun.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tb_BankMasuk_Tambah_Form_NoAkun.setObjectName(_fromUtf8("tb_BankMasuk_Tambah_Form_NoAkun"))
        self.gridLayout2.addWidget(self.tb_BankMasuk_Tambah_Form_NoAkun, 1, 2, 1, 1)
        self.le_BankMasuk_Tambah_Form_Catatan = QtGui.QLineEdit(self.fr_BankMasuk_Tambah_Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_BankMasuk_Tambah_Form_Catatan.sizePolicy().hasHeightForWidth())
        self.le_BankMasuk_Tambah_Form_Catatan.setSizePolicy(sizePolicy)
        self.le_BankMasuk_Tambah_Form_Catatan.setMaximumSize(QtCore.QSize(500, 16777215))
        self.le_BankMasuk_Tambah_Form_Catatan.setObjectName(_fromUtf8("le_BankMasuk_Tambah_Form_Catatan"))
        self.gridLayout2.addWidget(self.le_BankMasuk_Tambah_Form_Catatan, 3, 5, 1, 2)
        self.lb_BankMasuk_Tambah_Form_NoAkun = QtGui.QLabel(self.fr_BankMasuk_Tambah_Form)
        self.lb_BankMasuk_Tambah_Form_NoAkun.setObjectName(_fromUtf8("lb_BankMasuk_Tambah_Form_NoAkun"))
        self.gridLayout2.addWidget(self.lb_BankMasuk_Tambah_Form_NoAkun, 1, 0, 1, 1)
        self.lb_BankMasuk_Tambah_Form_Penyetor = QtGui.QLabel(self.fr_BankMasuk_Tambah_Form)
        self.lb_BankMasuk_Tambah_Form_Penyetor.setObjectName(_fromUtf8("lb_BankMasuk_Tambah_Form_Penyetor"))
        self.gridLayout2.addWidget(self.lb_BankMasuk_Tambah_Form_Penyetor, 2, 0, 1, 1)
        self.lb_BankMasuk_Tambah_Form_Nilai = QtGui.QLabel(self.fr_BankMasuk_Tambah_Form)
        self.lb_BankMasuk_Tambah_Form_Nilai.setMinimumSize(QtCore.QSize(150, 0))
        self.lb_BankMasuk_Tambah_Form_Nilai.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lb_BankMasuk_Tambah_Form_Nilai.setObjectName(_fromUtf8("lb_BankMasuk_Tambah_Form_Nilai"))
        self.gridLayout2.addWidget(self.lb_BankMasuk_Tambah_Form_Nilai, 2, 5, 1, 1)
        self.lb_BankMasuk_Tambah_Form_LabelNilai = QtGui.QLabel(self.fr_BankMasuk_Tambah_Form)
        self.lb_BankMasuk_Tambah_Form_LabelNilai.setObjectName(_fromUtf8("lb_BankMasuk_Tambah_Form_LabelNilai"))
        self.gridLayout2.addWidget(self.lb_BankMasuk_Tambah_Form_LabelNilai, 2, 4, 1, 1)
        self.lb_BankMasuk_Tambah_Form_Catatan = QtGui.QLabel(self.fr_BankMasuk_Tambah_Form)
        self.lb_BankMasuk_Tambah_Form_Catatan.setObjectName(_fromUtf8("lb_BankMasuk_Tambah_Form_Catatan"))
        self.gridLayout2.addWidget(self.lb_BankMasuk_Tambah_Form_Catatan, 3, 4, 1, 1)
        self.le_BankMasuk_Tambah_Form_Nomor = QtGui.QLineEdit(self.fr_BankMasuk_Tambah_Form)
        self.le_BankMasuk_Tambah_Form_Nomor.setMinimumSize(QtCore.QSize(150, 25))
        self.le_BankMasuk_Tambah_Form_Nomor.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_BankMasuk_Tambah_Form_Nomor.setObjectName(_fromUtf8("le_BankMasuk_Tambah_Form_Nomor"))
        self.gridLayout2.addWidget(self.le_BankMasuk_Tambah_Form_Nomor, 1, 5, 1, 1)
        self.lb_BankMasuk_Tambah_Form_Nomor = QtGui.QLabel(self.fr_BankMasuk_Tambah_Form)
        self.lb_BankMasuk_Tambah_Form_Nomor.setObjectName(_fromUtf8("lb_BankMasuk_Tambah_Form_Nomor"))
        self.gridLayout2.addWidget(self.lb_BankMasuk_Tambah_Form_Nomor, 1, 4, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout2.addItem(spacerItem26, 2, 3, 1, 1)
        self.dte_BankMasuk_Tambah_Form_Tanggal = QtGui.QDateTimeEdit(self.fr_BankMasuk_Tambah_Form)
        self.dte_BankMasuk_Tambah_Form_Tanggal.setCalendarPopup(True)
        self.dte_BankMasuk_Tambah_Form_Tanggal.setObjectName(_fromUtf8("dte_BankMasuk_Tambah_Form_Tanggal"))
        self.gridLayout2.addWidget(self.dte_BankMasuk_Tambah_Form_Tanggal, 3, 2, 1, 1)
        self.ivl_BankMasuk_Tambah.addWidget(self.fr_BankMasuk_Tambah_Form)
        self.fr_BankMasuk_Tambah_Content = QtGui.QFrame(self.st_BankMasuk_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankMasuk_Tambah_Content.sizePolicy().hasHeightForWidth())
        self.fr_BankMasuk_Tambah_Content.setSizePolicy(sizePolicy)
        self.fr_BankMasuk_Tambah_Content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankMasuk_Tambah_Content.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankMasuk_Tambah_Content.setObjectName(_fromUtf8("fr_BankMasuk_Tambah_Content"))
        self.ivl_BankMasuk_Tambah_Content = QtGui.QVBoxLayout(self.fr_BankMasuk_Tambah_Content)
        self.ivl_BankMasuk_Tambah_Content.setObjectName(_fromUtf8("ivl_BankMasuk_Tambah_Content"))
        self.tbl_BankMasuk_Tambah = QtGui.QTableWidget(self.fr_BankMasuk_Tambah_Content)
        self.tbl_BankMasuk_Tambah.setObjectName(_fromUtf8("tbl_BankMasuk_Tambah"))
        self.tbl_BankMasuk_Tambah.setColumnCount(4)
        self.tbl_BankMasuk_Tambah.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk_Tambah.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk_Tambah.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk_Tambah.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankMasuk_Tambah.setHorizontalHeaderItem(3, item)
        self.ivl_BankMasuk_Tambah_Content.addWidget(self.tbl_BankMasuk_Tambah)
        self.ivl_BankMasuk_Tambah.addWidget(self.fr_BankMasuk_Tambah_Content)
        self.fr_BankMasuk_Tambah_B = QtGui.QFrame(self.st_BankMasuk_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankMasuk_Tambah_B.sizePolicy().hasHeightForWidth())
        self.fr_BankMasuk_Tambah_B.setSizePolicy(sizePolicy)
        self.fr_BankMasuk_Tambah_B.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_BankMasuk_Tambah_B.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_BankMasuk_Tambah_B.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankMasuk_Tambah_B.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankMasuk_Tambah_B.setObjectName(_fromUtf8("fr_BankMasuk_Tambah_B"))
        self.ihl_BankMasuk_Tambah_B = QtGui.QHBoxLayout(self.fr_BankMasuk_Tambah_B)
        self.ihl_BankMasuk_Tambah_B.setObjectName(_fromUtf8("ihl_BankMasuk_Tambah_B"))
        self.tb_BankMasuk_Tambah_TambahBaris = QtGui.QPushButton(self.fr_BankMasuk_Tambah_B)
        self.tb_BankMasuk_Tambah_TambahBaris.setObjectName(_fromUtf8("tb_BankMasuk_Tambah_TambahBaris"))
        self.ihl_BankMasuk_Tambah_B.addWidget(self.tb_BankMasuk_Tambah_TambahBaris)
        self.tb_BankMasuk_Tambah_HapusBaris = QtGui.QPushButton(self.fr_BankMasuk_Tambah_B)
        self.tb_BankMasuk_Tambah_HapusBaris.setObjectName(_fromUtf8("tb_BankMasuk_Tambah_HapusBaris"))
        self.ihl_BankMasuk_Tambah_B.addWidget(self.tb_BankMasuk_Tambah_HapusBaris)
        spacerItem27 = QtGui.QSpacerItem(374, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_BankMasuk_Tambah_B.addItem(spacerItem27)
        self.tb_BankMasuk_Tambah_Simpan = QtGui.QPushButton(self.fr_BankMasuk_Tambah_B)
        self.tb_BankMasuk_Tambah_Simpan.setObjectName(_fromUtf8("tb_BankMasuk_Tambah_Simpan"))
        self.ihl_BankMasuk_Tambah_B.addWidget(self.tb_BankMasuk_Tambah_Simpan)
        self.tb_BankMasuk_Tambah_Cetak = QtGui.QPushButton(self.fr_BankMasuk_Tambah_B)
        self.tb_BankMasuk_Tambah_Cetak.setObjectName(_fromUtf8("tb_BankMasuk_Tambah_Cetak"))
        self.ihl_BankMasuk_Tambah_B.addWidget(self.tb_BankMasuk_Tambah_Cetak)
        self.tb_BankMasuk_Tambah_Batal = QtGui.QPushButton(self.fr_BankMasuk_Tambah_B)
        self.tb_BankMasuk_Tambah_Batal.setObjectName(_fromUtf8("tb_BankMasuk_Tambah_Batal"))
        self.ihl_BankMasuk_Tambah_B.addWidget(self.tb_BankMasuk_Tambah_Batal)
        self.ivl_BankMasuk_Tambah.addWidget(self.fr_BankMasuk_Tambah_B)
        st_KasBank.addWidget(self.st_BankMasuk_Tambah)
        self.st_BankKeluar = QtGui.QWidget()
        self.st_BankKeluar.setObjectName(_fromUtf8("st_BankKeluar"))
        self.ivl_BankKeluar = QtGui.QVBoxLayout(self.st_BankKeluar)
        self.ivl_BankKeluar.setObjectName(_fromUtf8("ivl_BankKeluar"))
        self.fr_BankKeluar_t = QtGui.QFrame(self.st_BankKeluar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankKeluar_t.sizePolicy().hasHeightForWidth())
        self.fr_BankKeluar_t.setSizePolicy(sizePolicy)
        self.fr_BankKeluar_t.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_BankKeluar_t.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_BankKeluar_t.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankKeluar_t.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankKeluar_t.setObjectName(_fromUtf8("fr_BankKeluar_t"))
        self.ihl_BankKeluar_t = QtGui.QHBoxLayout(self.fr_BankKeluar_t)
        self.ihl_BankKeluar_t.setObjectName(_fromUtf8("ihl_BankKeluar_t"))
        self.lb_BankKeluar_Judul = QtGui.QLabel(self.fr_BankKeluar_t)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lb_BankKeluar_Judul.sizePolicy().hasHeightForWidth())
        self.lb_BankKeluar_Judul.setSizePolicy(sizePolicy)
        self.lb_BankKeluar_Judul.setMinimumSize(QtCore.QSize(300, 0))
        self.lb_BankKeluar_Judul.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_BankKeluar_Judul.setFont(font)
        self.lb_BankKeluar_Judul.setObjectName(_fromUtf8("lb_BankKeluar_Judul"))
        self.ihl_BankKeluar_t.addWidget(self.lb_BankKeluar_Judul)
        spacerItem28 = QtGui.QSpacerItem(226, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_BankKeluar_t.addItem(spacerItem28)
        self.le_BankKeluar_Search = QtGui.QLineEdit(self.fr_BankKeluar_t)
        self.le_BankKeluar_Search.setMinimumSize(QtCore.QSize(200, 0))
        self.le_BankKeluar_Search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.le_BankKeluar_Search.setObjectName(_fromUtf8("le_BankKeluar_Search"))
        self.ihl_BankKeluar_t.addWidget(self.le_BankKeluar_Search)
        self.ivl_BankKeluar.addWidget(self.fr_BankKeluar_t)
        self.fr_BankKeluar_Content = QtGui.QFrame(self.st_BankKeluar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankKeluar_Content.sizePolicy().hasHeightForWidth())
        self.fr_BankKeluar_Content.setSizePolicy(sizePolicy)
        self.fr_BankKeluar_Content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankKeluar_Content.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankKeluar_Content.setObjectName(_fromUtf8("fr_BankKeluar_Content"))
        self.ivl_BankKeluar_Content = QtGui.QVBoxLayout(self.fr_BankKeluar_Content)
        self.ivl_BankKeluar_Content.setObjectName(_fromUtf8("ivl_BankKeluar_Content"))
        self.tbl_BankKeluar = QtGui.QTableWidget(self.fr_BankKeluar_Content)
        self.tbl_BankKeluar.setObjectName(_fromUtf8("tbl_BankKeluar"))
        self.tbl_BankKeluar.setColumnCount(7)
        self.tbl_BankKeluar.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar.setHorizontalHeaderItem(6, item)
        self.ivl_BankKeluar_Content.addWidget(self.tbl_BankKeluar)
        self.ivl_BankKeluar.addWidget(self.fr_BankKeluar_Content)
        self.fr_BankKeluar_b = QtGui.QFrame(self.st_BankKeluar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankKeluar_b.sizePolicy().hasHeightForWidth())
        self.fr_BankKeluar_b.setSizePolicy(sizePolicy)
        self.fr_BankKeluar_b.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_BankKeluar_b.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_BankKeluar_b.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankKeluar_b.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankKeluar_b.setObjectName(_fromUtf8("fr_BankKeluar_b"))
        self.ihl_BankKeluar_b = QtGui.QHBoxLayout(self.fr_BankKeluar_b)
        self.ihl_BankKeluar_b.setObjectName(_fromUtf8("ihl_BankKeluar_b"))
        self.tb_BankKeluar_Buka = QtGui.QPushButton(self.fr_BankKeluar_b)
        self.tb_BankKeluar_Buka.setObjectName(_fromUtf8("tb_BankKeluar_Buka"))
        self.ihl_BankKeluar_b.addWidget(self.tb_BankKeluar_Buka)
        spacerItem29 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.ihl_BankKeluar_b.addItem(spacerItem29)
        self.tb_BankKeluar_Tambah = QtGui.QPushButton(self.fr_BankKeluar_b)
        self.tb_BankKeluar_Tambah.setObjectName(_fromUtf8("tb_BankKeluar_Tambah"))
        self.ihl_BankKeluar_b.addWidget(self.tb_BankKeluar_Tambah)
        self.tb_BankKeluar_Delete = QtGui.QPushButton(self.fr_BankKeluar_b)
        self.tb_BankKeluar_Delete.setObjectName(_fromUtf8("tb_BankKeluar_Delete"))
        self.ihl_BankKeluar_b.addWidget(self.tb_BankKeluar_Delete)
        spacerItem30 = QtGui.QSpacerItem(495, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_BankKeluar_b.addItem(spacerItem30)
        self.tb_BankKeluar_Tutup = QtGui.QPushButton(self.fr_BankKeluar_b)
        self.tb_BankKeluar_Tutup.setObjectName(_fromUtf8("tb_BankKeluar_Tutup"))
        self.ihl_BankKeluar_b.addWidget(self.tb_BankKeluar_Tutup)
        self.ivl_BankKeluar.addWidget(self.fr_BankKeluar_b)
        st_KasBank.addWidget(self.st_BankKeluar)
        self.st_BankKeluar_Tambah = QtGui.QWidget()
        self.st_BankKeluar_Tambah.setObjectName(_fromUtf8("st_BankKeluar_Tambah"))
        self.ivl_BankKeluar_Tambah = QtGui.QVBoxLayout(self.st_BankKeluar_Tambah)
        self.ivl_BankKeluar_Tambah.setObjectName(_fromUtf8("ivl_BankKeluar_Tambah"))
        self.fr_BankKeluar_Tambah_T = QtGui.QFrame(self.st_BankKeluar_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankKeluar_Tambah_T.sizePolicy().hasHeightForWidth())
        self.fr_BankKeluar_Tambah_T.setSizePolicy(sizePolicy)
        self.fr_BankKeluar_Tambah_T.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_BankKeluar_Tambah_T.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_BankKeluar_Tambah_T.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankKeluar_Tambah_T.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankKeluar_Tambah_T.setObjectName(_fromUtf8("fr_BankKeluar_Tambah_T"))
        self.horizontalLayout3 = QtGui.QHBoxLayout(self.fr_BankKeluar_Tambah_T)
        self.horizontalLayout3.setObjectName(_fromUtf8("horizontalLayout3"))
        self.lb_BankKeluar_Judul_3 = QtGui.QLabel(self.fr_BankKeluar_Tambah_T)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lb_BankKeluar_Judul_3.sizePolicy().hasHeightForWidth())
        self.lb_BankKeluar_Judul_3.setSizePolicy(sizePolicy)
        self.lb_BankKeluar_Judul_3.setMinimumSize(QtCore.QSize(300, 0))
        self.lb_BankKeluar_Judul_3.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_BankKeluar_Judul_3.setFont(font)
        self.lb_BankKeluar_Judul_3.setObjectName(_fromUtf8("lb_BankKeluar_Judul_3"))
        self.horizontalLayout3.addWidget(self.lb_BankKeluar_Judul_3)
        spacerItem31 = QtGui.QSpacerItem(432, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout3.addItem(spacerItem31)
        self.ivl_BankKeluar_Tambah.addWidget(self.fr_BankKeluar_Tambah_T)
        self.fr_BankKeluar_Tambah_Form = QtGui.QFrame(self.st_BankKeluar_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankKeluar_Tambah_Form.sizePolicy().hasHeightForWidth())
        self.fr_BankKeluar_Tambah_Form.setSizePolicy(sizePolicy)
        self.fr_BankKeluar_Tambah_Form.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fr_BankKeluar_Tambah_Form.setStyleSheet(_fromUtf8("QLineEdit,QPushButton{border-style:inset;border-width:1px;border-radius:2px;border-color:rgb(156, 156, 156);background-color:#ffffff;min-height:23px;}"))
        self.fr_BankKeluar_Tambah_Form.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankKeluar_Tambah_Form.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankKeluar_Tambah_Form.setObjectName(_fromUtf8("fr_BankKeluar_Tambah_Form"))
        self.gridLayout3 = QtGui.QGridLayout(self.fr_BankKeluar_Tambah_Form)
        self.gridLayout3.setObjectName(_fromUtf8("gridLayout3"))
        self.lb_BankKeluar_Tambah_Form_Tanggal = QtGui.QLabel(self.fr_BankKeluar_Tambah_Form)
        self.lb_BankKeluar_Tambah_Form_Tanggal.setObjectName(_fromUtf8("lb_BankKeluar_Tambah_Form_Tanggal"))
        self.gridLayout3.addWidget(self.lb_BankKeluar_Tambah_Form_Tanggal, 3, 0, 1, 1)
        self.tb_BankKeluar_Tambah_Form_Penerima = QtGui.QPushButton(self.fr_BankKeluar_Tambah_Form)
        self.tb_BankKeluar_Tambah_Form_Penerima.setMinimumSize(QtCore.QSize(150, 25))
        self.tb_BankKeluar_Tambah_Form_Penerima.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tb_BankKeluar_Tambah_Form_Penerima.setObjectName(_fromUtf8("tb_BankKeluar_Tambah_Form_Penerima"))
        self.gridLayout3.addWidget(self.tb_BankKeluar_Tambah_Form_Penerima, 2, 2, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout3.addItem(spacerItem32, 2, 6, 1, 1)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout3.addItem(spacerItem33, 1, 6, 1, 1)
        self.tb_BankKeluar_Tambah_Form_NoAkun = QtGui.QPushButton(self.fr_BankKeluar_Tambah_Form)
        self.tb_BankKeluar_Tambah_Form_NoAkun.setMinimumSize(QtCore.QSize(150, 25))
        self.tb_BankKeluar_Tambah_Form_NoAkun.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tb_BankKeluar_Tambah_Form_NoAkun.setObjectName(_fromUtf8("tb_BankKeluar_Tambah_Form_NoAkun"))
        self.gridLayout3.addWidget(self.tb_BankKeluar_Tambah_Form_NoAkun, 1, 2, 1, 1)
        self.le_BankKeluar_Tambah_Form_Catatan = QtGui.QLineEdit(self.fr_BankKeluar_Tambah_Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_BankKeluar_Tambah_Form_Catatan.sizePolicy().hasHeightForWidth())
        self.le_BankKeluar_Tambah_Form_Catatan.setSizePolicy(sizePolicy)
        self.le_BankKeluar_Tambah_Form_Catatan.setMaximumSize(QtCore.QSize(500, 16777215))
        self.le_BankKeluar_Tambah_Form_Catatan.setObjectName(_fromUtf8("le_BankKeluar_Tambah_Form_Catatan"))
        self.gridLayout3.addWidget(self.le_BankKeluar_Tambah_Form_Catatan, 3, 5, 1, 2)
        self.lb_BankKeluar_Tambah_Form_NoAkun = QtGui.QLabel(self.fr_BankKeluar_Tambah_Form)
        self.lb_BankKeluar_Tambah_Form_NoAkun.setObjectName(_fromUtf8("lb_BankKeluar_Tambah_Form_NoAkun"))
        self.gridLayout3.addWidget(self.lb_BankKeluar_Tambah_Form_NoAkun, 1, 0, 1, 1)
        self.lb_BankKeluar_Tambah_Form_Penerima = QtGui.QLabel(self.fr_BankKeluar_Tambah_Form)
        self.lb_BankKeluar_Tambah_Form_Penerima.setObjectName(_fromUtf8("lb_BankKeluar_Tambah_Form_Penerima"))
        self.gridLayout3.addWidget(self.lb_BankKeluar_Tambah_Form_Penerima, 2, 0, 1, 1)
        self.lb_BankKeluar_Tambah_Form_Nilai = QtGui.QLabel(self.fr_BankKeluar_Tambah_Form)
        self.lb_BankKeluar_Tambah_Form_Nilai.setMinimumSize(QtCore.QSize(150, 0))
        self.lb_BankKeluar_Tambah_Form_Nilai.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lb_BankKeluar_Tambah_Form_Nilai.setObjectName(_fromUtf8("lb_BankKeluar_Tambah_Form_Nilai"))
        self.gridLayout3.addWidget(self.lb_BankKeluar_Tambah_Form_Nilai, 2, 5, 1, 1)
        self.lb_BankKeluar_Tambah_Form_LabelNilai = QtGui.QLabel(self.fr_BankKeluar_Tambah_Form)
        self.lb_BankKeluar_Tambah_Form_LabelNilai.setObjectName(_fromUtf8("lb_BankKeluar_Tambah_Form_LabelNilai"))
        self.gridLayout3.addWidget(self.lb_BankKeluar_Tambah_Form_LabelNilai, 2, 4, 1, 1)
        self.lb_BankKeluar_Tambah_Form_Catatan = QtGui.QLabel(self.fr_BankKeluar_Tambah_Form)
        self.lb_BankKeluar_Tambah_Form_Catatan.setObjectName(_fromUtf8("lb_BankKeluar_Tambah_Form_Catatan"))
        self.gridLayout3.addWidget(self.lb_BankKeluar_Tambah_Form_Catatan, 3, 4, 1, 1)
        self.le_BankKeluar_Tambah_Form_Nomor = QtGui.QLineEdit(self.fr_BankKeluar_Tambah_Form)
        self.le_BankKeluar_Tambah_Form_Nomor.setMinimumSize(QtCore.QSize(150, 25))
        self.le_BankKeluar_Tambah_Form_Nomor.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_BankKeluar_Tambah_Form_Nomor.setObjectName(_fromUtf8("le_BankKeluar_Tambah_Form_Nomor"))
        self.gridLayout3.addWidget(self.le_BankKeluar_Tambah_Form_Nomor, 1, 5, 1, 1)
        self.lb_BankKeluar_Tambah_Form_Nomor = QtGui.QLabel(self.fr_BankKeluar_Tambah_Form)
        self.lb_BankKeluar_Tambah_Form_Nomor.setObjectName(_fromUtf8("lb_BankKeluar_Tambah_Form_Nomor"))
        self.gridLayout3.addWidget(self.lb_BankKeluar_Tambah_Form_Nomor, 1, 4, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout3.addItem(spacerItem34, 2, 3, 1, 1)
        self.dte_BankKeluar_Tambah_Form_Tanggal = QtGui.QDateTimeEdit(self.fr_BankKeluar_Tambah_Form)
        self.dte_BankKeluar_Tambah_Form_Tanggal.setCalendarPopup(True)
        self.dte_BankKeluar_Tambah_Form_Tanggal.setObjectName(_fromUtf8("dte_BankKeluar_Tambah_Form_Tanggal"))
        self.gridLayout3.addWidget(self.dte_BankKeluar_Tambah_Form_Tanggal, 3, 2, 1, 1)
        self.ivl_BankKeluar_Tambah.addWidget(self.fr_BankKeluar_Tambah_Form)
        self.fr_BankKeluar_Tambah_Content = QtGui.QFrame(self.st_BankKeluar_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankKeluar_Tambah_Content.sizePolicy().hasHeightForWidth())
        self.fr_BankKeluar_Tambah_Content.setSizePolicy(sizePolicy)
        self.fr_BankKeluar_Tambah_Content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankKeluar_Tambah_Content.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankKeluar_Tambah_Content.setObjectName(_fromUtf8("fr_BankKeluar_Tambah_Content"))
        self.ivl_BankKeluar_Tambah_Content = QtGui.QVBoxLayout(self.fr_BankKeluar_Tambah_Content)
        self.ivl_BankKeluar_Tambah_Content.setObjectName(_fromUtf8("ivl_BankKeluar_Tambah_Content"))
        self.tbl_BankKeluar_Tambah = QtGui.QTableWidget(self.fr_BankKeluar_Tambah_Content)
        self.tbl_BankKeluar_Tambah.setObjectName(_fromUtf8("tbl_BankKeluar_Tambah"))
        self.tbl_BankKeluar_Tambah.setColumnCount(4)
        self.tbl_BankKeluar_Tambah.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar_Tambah.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar_Tambah.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar_Tambah.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_BankKeluar_Tambah.setHorizontalHeaderItem(3, item)
        self.ivl_BankKeluar_Tambah_Content.addWidget(self.tbl_BankKeluar_Tambah)
        self.ivl_BankKeluar_Tambah.addWidget(self.fr_BankKeluar_Tambah_Content)
        self.fr_BankKeluar_Tambah_B = QtGui.QFrame(self.st_BankKeluar_Tambah)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fr_BankKeluar_Tambah_B.sizePolicy().hasHeightForWidth())
        self.fr_BankKeluar_Tambah_B.setSizePolicy(sizePolicy)
        self.fr_BankKeluar_Tambah_B.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_BankKeluar_Tambah_B.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_BankKeluar_Tambah_B.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_BankKeluar_Tambah_B.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_BankKeluar_Tambah_B.setObjectName(_fromUtf8("fr_BankKeluar_Tambah_B"))
        self.ihl_BankKeluar_Tambah_B = QtGui.QHBoxLayout(self.fr_BankKeluar_Tambah_B)
        self.ihl_BankKeluar_Tambah_B.setObjectName(_fromUtf8("ihl_BankKeluar_Tambah_B"))
        self.tb_BankKeluar_Tambah_TambahBaris = QtGui.QPushButton(self.fr_BankKeluar_Tambah_B)
        self.tb_BankKeluar_Tambah_TambahBaris.setObjectName(_fromUtf8("tb_BankKeluar_Tambah_TambahBaris"))
        self.ihl_BankKeluar_Tambah_B.addWidget(self.tb_BankKeluar_Tambah_TambahBaris)
        self.tb_BankKeluar_Tambah_HapusBaris = QtGui.QPushButton(self.fr_BankKeluar_Tambah_B)
        self.tb_BankKeluar_Tambah_HapusBaris.setObjectName(_fromUtf8("tb_BankKeluar_Tambah_HapusBaris"))
        self.ihl_BankKeluar_Tambah_B.addWidget(self.tb_BankKeluar_Tambah_HapusBaris)
        spacerItem35 = QtGui.QSpacerItem(374, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ihl_BankKeluar_Tambah_B.addItem(spacerItem35)
        self.tb_BankKeluar_Tambah_Simpan = QtGui.QPushButton(self.fr_BankKeluar_Tambah_B)
        self.tb_BankKeluar_Tambah_Simpan.setObjectName(_fromUtf8("tb_BankKeluar_Tambah_Simpan"))
        self.ihl_BankKeluar_Tambah_B.addWidget(self.tb_BankKeluar_Tambah_Simpan)
        self.tb_BankKeluar_Tambah_Cetak = QtGui.QPushButton(self.fr_BankKeluar_Tambah_B)
        self.tb_BankKeluar_Tambah_Cetak.setObjectName(_fromUtf8("tb_BankKeluar_Tambah_Cetak"))
        self.ihl_BankKeluar_Tambah_B.addWidget(self.tb_BankKeluar_Tambah_Cetak)
        self.tb_BankKeluar_Tambah_Batal = QtGui.QPushButton(self.fr_BankKeluar_Tambah_B)
        self.tb_BankKeluar_Tambah_Batal.setObjectName(_fromUtf8("tb_BankKeluar_Tambah_Batal"))
        self.ihl_BankKeluar_Tambah_B.addWidget(self.tb_BankKeluar_Tambah_Batal)
        self.ivl_BankKeluar_Tambah.addWidget(self.fr_BankKeluar_Tambah_B)
        st_KasBank.addWidget(self.st_BankKeluar_Tambah)

        self.retranslateUi(st_KasBank)
        st_KasBank.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(st_KasBank)

    def retranslateUi(self, st_KasBank):
        st_KasBank.setWindowTitle(_translate("st_KasBank", "StackedWidget", None))
        self.tb_Menu_KasMasuk.setText(_translate("st_KasBank", "Kas Masuk", None))
        self.tb_Menu_KasKeluar.setText(_translate("st_KasBank", "Kas Keluar", None))
        self.tb_Menu_BankMasuk.setText(_translate("st_KasBank", "Bank Masuk", None))
        self.tb_Menu_BankKeluar.setText(_translate("st_KasBank", "Bank Keluar", None))
        self.lb_KasMasuk_Judul.setText(_translate("st_KasBank", "Kas Masuk", None))
        self.le_KasMasuk_Search.setPlaceholderText(_translate("st_KasBank", "Type to search...", None))
        item = self.tbl_KasMasuk.horizontalHeaderItem(0)
        item.setText(_translate("st_KasBank", "Tanggal", None))
        item = self.tbl_KasMasuk.horizontalHeaderItem(1)
        item.setText(_translate("st_KasBank", "Nomor Referensi", None))
        item = self.tbl_KasMasuk.horizontalHeaderItem(2)
        item.setText(_translate("st_KasBank", "Catatan", None))
        item = self.tbl_KasMasuk.horizontalHeaderItem(3)
        item.setText(_translate("st_KasBank", "Nilai", None))
        item = self.tbl_KasMasuk.horizontalHeaderItem(4)
        item.setText(_translate("st_KasBank", "Nomor Akun Kas", None))
        item = self.tbl_KasMasuk.horizontalHeaderItem(5)
        item.setText(_translate("st_KasBank", "Penyetor", None))
        item = self.tbl_KasMasuk.horizontalHeaderItem(6)
        item.setText(_translate("st_KasBank", "Rev", None))
        self.tb_KasMasuk_Buka.setText(_translate("st_KasBank", "Buka", None))
        self.tb_KasMasuk_Tambah.setText(_translate("st_KasBank", "Baru", None))
        self.tb_KasMasuk_Delete.setText(_translate("st_KasBank", "Hapus", None))
        self.tb_KasMasuk_Tutup.setText(_translate("st_KasBank", "Tutup", None))
        self.lb_KasMasuk_Judul_2.setText(_translate("st_KasBank", "+Kas Masuk", None))
        self.lb_KasMasuk_Tambah_Form_Tanggal.setText(_translate("st_KasBank", "Tanggal :", None))
        self.tb_KasMasuk_Tambah_Form_Penyetor.setText(_translate("st_KasBank", "-", None))
        self.tb_KasMasuk_Tambah_Form_NoAkun.setText(_translate("st_KasBank", "-", None))
        self.lb_KasMasuk_Tambah_Form_NoAkun.setText(_translate("st_KasBank", "Akun Kas :", None))
        self.lb_KasMasuk_Tambah_Form_Penyetor.setText(_translate("st_KasBank", "Dari :", None))
        self.lb_KasMasuk_Tambah_Form_Nilai.setText(_translate("st_KasBank", "Rp 0", None))
        self.lb_KasMasuk_Tambah_Form_LabelNilai.setText(_translate("st_KasBank", "Besar Total :", None))
        self.lb_KasMasuk_Tambah_Form_Catatan.setText(_translate("st_KasBank", "Catatan :", None))
        self.lb_KasMasuk_Tambah_Form_Nomor.setText(_translate("st_KasBank", "Nomor Referensi :", None))
        item = self.tbl_KasMasuk_Tambah.horizontalHeaderItem(0)
        item.setText(_translate("st_KasBank", "Nomor Akun", None))
        item = self.tbl_KasMasuk_Tambah.horizontalHeaderItem(1)
        item.setText(_translate("st_KasBank", "Nama Akun", None))
        item = self.tbl_KasMasuk_Tambah.horizontalHeaderItem(2)
        item.setText(_translate("st_KasBank", "Nilai", None))
        item = self.tbl_KasMasuk_Tambah.horizontalHeaderItem(3)
        item.setText(_translate("st_KasBank", "Keterangan", None))
        self.tb_KasMasuk_Tambah_TambahBaris.setText(_translate("st_KasBank", "Tambah Baris", None))
        self.tb_KasMasuk_Tambah_HapusBaris.setText(_translate("st_KasBank", "Hapus Baris", None))
        self.tb_KasMasuk_Tambah_Simpan.setText(_translate("st_KasBank", "Simpan", None))
        self.tb_KasMasuk_Tambah_Cetak.setText(_translate("st_KasBank", "Cetak", None))
        self.tb_KasMasuk_Tambah_Batal.setText(_translate("st_KasBank", "Batal", None))
        self.lb_KasKeluar_Judul.setText(_translate("st_KasBank", "Kas Keluar", None))
        self.le_KasKeluar_Search.setPlaceholderText(_translate("st_KasBank", "Type to search...", None))
        item = self.tbl_KasKeluar.horizontalHeaderItem(0)
        item.setText(_translate("st_KasBank", "Tanggal", None))
        item = self.tbl_KasKeluar.horizontalHeaderItem(1)
        item.setText(_translate("st_KasBank", "Nomor Referensi", None))
        item = self.tbl_KasKeluar.horizontalHeaderItem(2)
        item.setText(_translate("st_KasBank", "Catatan", None))
        item = self.tbl_KasKeluar.horizontalHeaderItem(3)
        item.setText(_translate("st_KasBank", "Nilai", None))
        item = self.tbl_KasKeluar.horizontalHeaderItem(4)
        item.setText(_translate("st_KasBank", "Nomor Akun Kas", None))
        item = self.tbl_KasKeluar.horizontalHeaderItem(5)
        item.setText(_translate("st_KasBank", "Penerima", None))
        item = self.tbl_KasKeluar.horizontalHeaderItem(6)
        item.setText(_translate("st_KasBank", "Rev", None))
        self.tb_KasKeluar_Buka.setText(_translate("st_KasBank", "Buka", None))
        self.tb_KasKeluar_Tambah.setText(_translate("st_KasBank", "Baru", None))
        self.tb_KasKeluar_Delete.setText(_translate("st_KasBank", "Hapus", None))
        self.tb_KasKeluar_Tutup.setText(_translate("st_KasBank", "Tutup", None))
        self.lb_KasKeluar_Judul_3.setText(_translate("st_KasBank", "+Kas Keluar", None))
        self.lb_KasKeluar_Tambah_Form_Tanggal.setText(_translate("st_KasBank", "Tanggal :", None))
        self.tb_KasKeluar_Tambah_Form_Penerima.setText(_translate("st_KasBank", "-", None))
        self.tb_KasKeluar_Tambah_Form_NoAkun.setText(_translate("st_KasBank", "-", None))
        self.lb_KasKeluar_Tambah_Form_NoAkun.setText(_translate("st_KasBank", "Akun Kas :", None))
        self.lb_KasKeluar_Tambah_Form_Penerima.setText(_translate("st_KasBank", "Penerima :", None))
        self.lb_KasKeluar_Tambah_Form_Nilai.setText(_translate("st_KasBank", "Rp 0", None))
        self.lb_KasKeluar_Tambah_Form_LabelNilai.setText(_translate("st_KasBank", "Besar Total :", None))
        self.lb_KasKeluar_Tambah_Form_Catatan.setText(_translate("st_KasBank", "Catatan :", None))
        self.lb_KasKeluar_Tambah_Form_Nomor.setText(_translate("st_KasBank", "Nomor Referensi :", None))
        item = self.tbl_KasKeluar_Tambah.horizontalHeaderItem(0)
        item.setText(_translate("st_KasBank", "Nomor Akun", None))
        item = self.tbl_KasKeluar_Tambah.horizontalHeaderItem(1)
        item.setText(_translate("st_KasBank", "Nama Akun", None))
        item = self.tbl_KasKeluar_Tambah.horizontalHeaderItem(2)
        item.setText(_translate("st_KasBank", "Nilai", None))
        item = self.tbl_KasKeluar_Tambah.horizontalHeaderItem(3)
        item.setText(_translate("st_KasBank", "Keterangan", None))
        self.tb_KasKeluar_Tambah_TambahBaris.setText(_translate("st_KasBank", "Tambah Baris", None))
        self.tb_KasKeluar_Tambah_HapusBaris.setText(_translate("st_KasBank", "Hapus Baris", None))
        self.tb_KasKeluar_Tambah_Simpan.setText(_translate("st_KasBank", "Simpan", None))
        self.tb_KasKeluar_Tambah_Cetak.setText(_translate("st_KasBank", "Cetak", None))
        self.tb_KasKeluar_Tambah_Batal.setText(_translate("st_KasBank", "Batal", None))
        self.lb_BankMasuk_Judul.setText(_translate("st_KasBank", "Bank Masuk", None))
        self.le_BankMasuk_Search.setPlaceholderText(_translate("st_KasBank", "Type to search...", None))
        item = self.tbl_BankMasuk.horizontalHeaderItem(0)
        item.setText(_translate("st_KasBank", "Tanggal", None))
        item = self.tbl_BankMasuk.horizontalHeaderItem(1)
        item.setText(_translate("st_KasBank", "Nomor Referensi", None))
        item = self.tbl_BankMasuk.horizontalHeaderItem(2)
        item.setText(_translate("st_KasBank", "Catatan", None))
        item = self.tbl_BankMasuk.horizontalHeaderItem(3)
        item.setText(_translate("st_KasBank", "Nilai", None))
        item = self.tbl_BankMasuk.horizontalHeaderItem(4)
        item.setText(_translate("st_KasBank", "Nomor Akun Bank", None))
        item = self.tbl_BankMasuk.horizontalHeaderItem(5)
        item.setText(_translate("st_KasBank", "Penyetor", None))
        item = self.tbl_BankMasuk.horizontalHeaderItem(6)
        item.setText(_translate("st_KasBank", "Rev", None))
        self.tb_BankMasuk_Buka.setText(_translate("st_KasBank", "Buka", None))
        self.tb_BankMasuk_Tambah.setText(_translate("st_KasBank", "Baru", None))
        self.tb_BankMasuk_Delete.setText(_translate("st_KasBank", "Hapus", None))
        self.tb_BankMasuk_Tutup.setText(_translate("st_KasBank", "Tutup", None))
        self.lb_BankMasuk_Judul_2.setText(_translate("st_KasBank", "+Bank Masuk", None))
        self.lb_BankMasuk_Tambah_Form_Tanggal.setText(_translate("st_KasBank", "Tanggal :", None))
        self.tb_BankMasuk_Tambah_Form_Penyetor.setText(_translate("st_KasBank", "-", None))
        self.tb_BankMasuk_Tambah_Form_NoAkun.setText(_translate("st_KasBank", "-", None))
        self.lb_BankMasuk_Tambah_Form_NoAkun.setText(_translate("st_KasBank", "Akun Bank :", None))
        self.lb_BankMasuk_Tambah_Form_Penyetor.setText(_translate("st_KasBank", "Dari :", None))
        self.lb_BankMasuk_Tambah_Form_Nilai.setText(_translate("st_KasBank", "Rp 0", None))
        self.lb_BankMasuk_Tambah_Form_LabelNilai.setText(_translate("st_KasBank", "Besar Total :", None))
        self.lb_BankMasuk_Tambah_Form_Catatan.setText(_translate("st_KasBank", "Catatan :", None))
        self.lb_BankMasuk_Tambah_Form_Nomor.setText(_translate("st_KasBank", "Nomor Referensi :", None))
        item = self.tbl_BankMasuk_Tambah.horizontalHeaderItem(0)
        item.setText(_translate("st_KasBank", "Nomor Akun", None))
        item = self.tbl_BankMasuk_Tambah.horizontalHeaderItem(1)
        item.setText(_translate("st_KasBank", "Nama Akun", None))
        item = self.tbl_BankMasuk_Tambah.horizontalHeaderItem(2)
        item.setText(_translate("st_KasBank", "Nilai", None))
        item = self.tbl_BankMasuk_Tambah.horizontalHeaderItem(3)
        item.setText(_translate("st_KasBank", "Keterangan", None))
        self.tb_BankMasuk_Tambah_TambahBaris.setText(_translate("st_KasBank", "Tambah Baris", None))
        self.tb_BankMasuk_Tambah_HapusBaris.setText(_translate("st_KasBank", "Hapus Baris", None))
        self.tb_BankMasuk_Tambah_Simpan.setText(_translate("st_KasBank", "Simpan", None))
        self.tb_BankMasuk_Tambah_Cetak.setText(_translate("st_KasBank", "Cetak", None))
        self.tb_BankMasuk_Tambah_Batal.setText(_translate("st_KasBank", "Batal", None))
        self.lb_BankKeluar_Judul.setText(_translate("st_KasBank", "Bank Keluar", None))
        self.le_BankKeluar_Search.setPlaceholderText(_translate("st_KasBank", "Type to search...", None))
        item = self.tbl_BankKeluar.horizontalHeaderItem(0)
        item.setText(_translate("st_KasBank", "Tanggal", None))
        item = self.tbl_BankKeluar.horizontalHeaderItem(1)
        item.setText(_translate("st_KasBank", "Nomor Referensi", None))
        item = self.tbl_BankKeluar.horizontalHeaderItem(2)
        item.setText(_translate("st_KasBank", "Catatan", None))
        item = self.tbl_BankKeluar.horizontalHeaderItem(3)
        item.setText(_translate("st_KasBank", "Nilai", None))
        item = self.tbl_BankKeluar.horizontalHeaderItem(4)
        item.setText(_translate("st_KasBank", "Nomor Akun Bank", None))
        item = self.tbl_BankKeluar.horizontalHeaderItem(5)
        item.setText(_translate("st_KasBank", "Penerima", None))
        item = self.tbl_BankKeluar.horizontalHeaderItem(6)
        item.setText(_translate("st_KasBank", "Rev", None))
        self.tb_BankKeluar_Buka.setText(_translate("st_KasBank", "Buka", None))
        self.tb_BankKeluar_Tambah.setText(_translate("st_KasBank", "Baru", None))
        self.tb_BankKeluar_Delete.setText(_translate("st_KasBank", "Hapus", None))
        self.tb_BankKeluar_Tutup.setText(_translate("st_KasBank", "Tutup", None))
        self.lb_BankKeluar_Judul_3.setText(_translate("st_KasBank", "+Bank Keluar", None))
        self.lb_BankKeluar_Tambah_Form_Tanggal.setText(_translate("st_KasBank", "Tanggal :", None))
        self.tb_BankKeluar_Tambah_Form_Penerima.setText(_translate("st_KasBank", "-", None))
        self.tb_BankKeluar_Tambah_Form_NoAkun.setText(_translate("st_KasBank", "-", None))
        self.lb_BankKeluar_Tambah_Form_NoAkun.setText(_translate("st_KasBank", "Akun Bank :", None))
        self.lb_BankKeluar_Tambah_Form_Penerima.setText(_translate("st_KasBank", "Penerima :", None))
        self.lb_BankKeluar_Tambah_Form_Nilai.setText(_translate("st_KasBank", "Rp 0", None))
        self.lb_BankKeluar_Tambah_Form_LabelNilai.setText(_translate("st_KasBank", "Besar Total :", None))
        self.lb_BankKeluar_Tambah_Form_Catatan.setText(_translate("st_KasBank", "Catatan :", None))
        self.lb_BankKeluar_Tambah_Form_Nomor.setText(_translate("st_KasBank", "Nomor Referensi :", None))
        item = self.tbl_BankKeluar_Tambah.horizontalHeaderItem(0)
        item.setText(_translate("st_KasBank", "Nomor Akun", None))
        item = self.tbl_BankKeluar_Tambah.horizontalHeaderItem(1)
        item.setText(_translate("st_KasBank", "Nama Akun", None))
        item = self.tbl_BankKeluar_Tambah.horizontalHeaderItem(2)
        item.setText(_translate("st_KasBank", "Nilai", None))
        item = self.tbl_BankKeluar_Tambah.horizontalHeaderItem(3)
        item.setText(_translate("st_KasBank", "Keterangan", None))
        self.tb_BankKeluar_Tambah_TambahBaris.setText(_translate("st_KasBank", "Tambah Baris", None))
        self.tb_BankKeluar_Tambah_HapusBaris.setText(_translate("st_KasBank", "Hapus Baris", None))
        self.tb_BankKeluar_Tambah_Simpan.setText(_translate("st_KasBank", "Simpan", None))
        self.tb_BankKeluar_Tambah_Cetak.setText(_translate("st_KasBank", "Cetak", None))
        self.tb_BankKeluar_Tambah_Batal.setText(_translate("st_KasBank", "Batal", None))

import ui_kasbankrc_rc
